Repository nanoframework/nf-interpreter, pull requests merged in 2018-11, with the labels that each got.

#953 Remove ESP32 version from ESP32_TOOLS_PATH and xtensa-esp32-elf in install-esp32-tools.ps1
  appveyor.yml
  install-esp32-tools.ps1
  targets/FreeRTOS/ESP32_DevKitC/BUILD-ESP32.md
Labels: Area: Config-and-Build

#955 Socket fixes for Http
  src/PAL/Lwip/lwIP_Sockets.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/lwipopts.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/lwipopts.h
  targets/FreeRTOS/ESP32_DevKitC/Lwip/lwipopts.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Memory.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/target_board.h.in
Labels: Area: Common libs, Area: Targets, Type: bug, Type: enhancement

#969 Fix mscorlib native checksum for v1.0.6.1
  src/CLR/CorLib/corlib_native.cpp
Labels: Area: Interpreter, Type: bug

#982 Replace AppVeyor with Azure Pipelines
  README.md
  appveyor.yml
  azure-pipelines.yml
  version.json
Labels: Area: Config-and-Build

#983 Fix System.Net declaration
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
Labels: Type: bug

#984 Work CD-CI
  azure-discord.ps1
  azure-pipelines.yml
Labels: Area: Config-and-Build

#985 Update Devices.I2c assembly declaration
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.h
Labels: Type: dependencies

#987 Add native implementation for 1-Wire class library
  CMake/Modules/CHIBIOS_STM32F0xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_sources.cmake
  CMake/Modules/FindChibiOSnfOverlay.cmake
  CMake/Modules/FindnanoFramework.Devices.OneWire.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  CMakeLists.txt
  azure-pipelines.yml
  cmake-variants.TEMPLATE.json
  src/CLR/Core/Hardware/Hardware.cpp
  src/CLR/Include/nanoCLR_Hardware.h
  src/CLR/Include/nanoCLR_Runtime.h
  src/HAL/Include/nanoHAL_v2.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/CLR_Startup_Thread.c
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native_nanoFramework_Devices_OneWire_OneWireController.cpp
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/hal_community.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/stm32_onewire/hal_stm32_onewire.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/ONEWIREv1/README.md
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/ONEWIREv1/onewire_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/ONEWIREv1/onewire_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/hal_community.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_onewire/hal_stm32_onewire.c
Labels: Area: Common libs, Type: enhancement

#988 Rework azure pipelines to use templates
  azure-pipelines-templates/build-chibios-stm32.yml
  azure-pipelines-templates/build-esp32.yml
  azure-pipelines-templates/download-hexdfu.yml
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines-templates/download-install-ninja.yml
  azure-pipelines-templates/nb-gitversioning.yml
  azure-pipelines-templates/pack-publish-artifacts.yml
  azure-pipelines-templates/publish-bintray.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1012 Improve APIs and HAL options handling
  CMakeLists.txt
Labels: Area: Config-and-Build

#1013 Improvements on 1-Wire driver and configs
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/stm32_onewire/hal_stm32_onewire.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/ONEWIREv1/onewire_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/ONEWIREv1/onewire_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_onewire/hal_stm32_onewire.c
Labels: Area: STM32-ChibiOS, Type: enhancement

#1014 Rework I2C native code
  CMake/Modules/FindWindows.Devices.I2c.cmake
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2c_I2cController.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2c_I2cController.cpp
Labels: Area: STM32-ChibiOS, Breaking-change, Type: enhancement

#1017 Add support for 1-wire interface for ESP32
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native_nanoFramework_Devices_OneWire_OneWireController.cpp
  targets/FreeRTOS/ESP32_DevKitC/target_nf_devices_onewire_config.c
  targets/FreeRTOS/ESP32_DevKitC/target_nf_devices_onewire_config.h
Labels: Area: ESP32, Type: enhancement

#1024 Update declaration of nanoFramework.Hardware.Stm32
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.cpp
Labels: Area: STM32-ChibiOS, Type: dependencies

#1010 Update Devices.Adc declaration
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Adc/win_dev_adc_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Adc/win_dev_adc_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
Labels: Type: dependencies

#1028 Update Devices.Pwm declarations
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native_Windows_Devices_Pwm_PwmController.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native_Windows_Devices_Pwm_PwmController.cpp
Labels: Type: dependencies

#1030 Update Devices.Spi assemblies
  CMake/Modules/FindWindows.Devices.Spi.cmake
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiController.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Spi/win_dev_spi_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Spi/win_dev_spi_native.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiController.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
Labels: Type: dependencies

#1033 Fix nanoCLR Win32 build
  azure-pipelines.yml
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/CorLib/CorLib.vcxproj.filters
  targets/os/win32/nanoCLR/Various.cpp
  targets/os/win32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native.cpp
  targets/os/win32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native.h
  targets/os/win32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/os/win32/nanoCLR/nanoCLR.vcxproj
  targets/os/win32/nanoCLR/nanoCLR.vcxproj.filters
  targets/os/win32/nanoCLR/stdafx.h
Labels: Area: WIN32, Type: bug

#1043 Fix include paths difference on release configuration
  src/CLR/CorLib/CorLib.vcxproj
  targets/os/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: WIN32, Type: enhancement
