Repository nanoframework/nf-interpreter, pull requests merged in 2018-12, with the labels that each got.

#1081 Fix ADC NativeInit
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
Labels: Area: ESP32, Area: STM32-ChibiOS, Type: bug

#1083 Improve HAL_RingBuffer to handle different type sizes
  src/HAL/Include/nanoHAL.h
Labels: Area: Common libs, Type: enhancement

#1084 Add check for buffer empty/full in HAL_RingBuffer
  src/HAL/Include/nanoHAL.h
Labels: Area: Common libs, Type: bug

#1085 Fix inclusion of Configuration Manager source code files
  CMake/Modules/FindNF_CoreCLR.cmake
  azure-pipelines.yml
  targets/FreeRTOS/ESP32_DevKitC/CMakeLists.txt
Labels: Area: Config-and-Build

#1086 Fix inclusion of ConfigurationManager
  CMake/Modules/FindNF_CoreCLR.cmake
Labels: Area: Config-and-Build

#1087 Add native implementation of Devices.Can
  CMake/Modules/CHIBIOS_STM32F0xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_sources.cmake
  CMake/Modules/FindnanoFramework.Devices.Can.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  CMakeLists.txt
  azure-pipelines.yml
  cmake-variants.TEMPLATE.json
  src/PAL/Include/nanoPAL_Events.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_devices_can_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_devices_can_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_can_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_can_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_devices_can_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_devices_can_config.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.Can/nf_devices_can_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.Can/nf_devices_can_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.Can/nf_devices_can_native_nanoFramework_Devices_Can_CanController.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/target_platform.h.in
Labels: Area: STM32-ChibiOS, Type: enhancement

#1089 Add check for reboot and exit conditions on WaitForEvents loop
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/targetPAL_Events.cpp
Labels: Area: Common libs, Type: enhancement

#1090 Fix WiFi assembly declaration
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Wifi/win_dev_wifi_native.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/Windows.Devices.Wifi/win_dev_wifi_native.h
Labels: Area: ESP32, Type: bug

#1092 Fix parsing of X509 certificate for mbedTLS
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_generic_init_internal.cpp
Labels: Type: bug

#1091 Fix ConfigurationManager_StoreConfigurationBlock for ESP32
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/targetHAL_ConfigurationManager.cpp
Labels: Area: ESP32, Type: bug

#1093 Fix parsing of X509 certificate for mbedTLS
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_parse_certificate_internal.cpp
Labels: Type: bug

#1094 Update SslStream native implementation
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_SslNative.cpp
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_add_cert_auth_internal.cpp
Labels: Area: Common libs, Breaking-change, Type: enhancement

#1115 Move install scripts to its own folder
  install-scripts/Set-PathVariable.ps1
  install-scripts/install-arm-gcc-toolchain.ps1
  install-scripts/install-esp32-idf.ps1
  install-scripts/install-esp32-libs.ps1
  install-scripts/install-esp32-openocd.ps1
  install-scripts/install-esp32-toolchain.ps1
  install-scripts/install-esp32-tools.ps1
  install-scripts/install-nf-hex2dfu.ps1
  install-scripts/install-ninja.ps1
  install-scripts/install-stm32-tools.ps1
Labels: Area: Infrastructure-and-Organization

#1116 Move ST_STM32F4_DISCOVERY to community targets
  README.md
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/README.md
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/common/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/common/Device_BlockStorage-DEBUG.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/common/Device_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/common/usbcfg.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/common/usbcfg.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/STM32F407xG_booter-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/STM32F407xG_booter.ld
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/chconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/STM32F407xG_CLR-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/STM32F407xG_CLR.ld
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/chconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/nanoHAL.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_can_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_can_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_adc_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F4_DISCOVERY/target_windows_devices_spi_config.cpp
Labels: Area: Infrastructure-and-Organization

#1117 Move ST_NUCLEO144_F746ZG to community targets
  README.md
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/README.md
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/board.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/board.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/common/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/common/Device_BlockStorage-DEBUG.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/common/Device_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/common/usbcfg.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/common/usbcfg.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/lwipopts.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/managed_helpers/Adc.cs
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/managed_helpers/README.md
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/mbedtls_config.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/STM32F746xG_booter-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/STM32F746xG_booter.ld
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/chconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/STM32F746xG_CLR-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/STM32F746xG_CLR.ld
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/chconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/nanoHAL.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_lwip_sntp_opts.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_adc_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO144_F746ZG/target_windows_devices_spi_config.cpp
Labels: Area: Infrastructure-and-Organization

#1120 Update mbedTLS to v2.14.1
  CMake/Modules/FindmbedTLS.cmake
  CMake/mbedTLS.CMakeLists.cmake.in
  CMakeLists.txt
Labels: Type: dependencies

#1122 Add support for CAN in NETDUINO3_WIFI
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_nf_devices_can_config.cpp
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_nf_devices_can_config.h
Labels: Area: STM32-ChibiOS, Type: enhancement

#1121 Work on power down sequence
  src/CLR/Core/Execution.cpp
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/nanoCLR_Hardware.h
  src/HAL/Include/nanoHAL_Power.h
  src/HAL/Include/nanoHAL_v2.h
  targets/CMSIS-OS/ChibiOS/Include/targetHAL_Power.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/CLRStartup.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL_Power.c
  targets/FreeRTOS/ESP32_DevKitC/Include/targetHAL_Power.h
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/CLRStartup.cpp
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/CMakeLists.txt
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/targetHAL_Power.c
  targets/os/win32/nanoCLR/CLRStartup.cpp
  targets/os/win32/nanoCLR/Various.cpp
Labels: Area: Common libs, Area: Targets, Type: enhancement

#1123 Add native code for Native.Stm32 Power class
  CMake/Modules/FindnanoFramework.Hardware.Stm32.cmake
  src/HAL/Include/nanoHAL_v2.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native_nanoFramework_Hardware_Stm32_Power.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL_Power.c
  targets/FreeRTOS/ESP32_DevKitC/nanoCLR/targetHAL.cpp
Labels: Area: Common libs, Area: STM32-ChibiOS, Type: enhancement

#1126 Work on WP serial driver configuration
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/common/serialcfg.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/common/WireProtocol_HAL_Interface.c
Labels: Area: Config-and-Build, Area: STM32-ChibiOS
