Repository nanoframework/nf-interpreter, pull requests merged in 2019-09, with the labels that each got.

#1440 Fix mbedTLS config path
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
Labels: Area: Config-and-Build, Area: ESP32

#1445 Fix GPIO interrupt processing for SimpleLink devices
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
Labels: Area: TI-SimpleLink, Type: bug

#1446 Improvements in block storage API
  src/PAL/BlockStorage/nanoPAL_BlockStorage.c
  src/PAL/Include/nanoPAL_BlockStorage.h
Labels: Area: Common libs, Type: enhancement

#1447 Improvements in Monitor_FlashSectorMap
  src/CLR/Debugger/Debugger.cpp
Labels: Area: Common libs, Type: enhancement

#1448 Fix buffer overflow in Garbage Collector
  src/CLR/Core/GarbageCollector_ComputeReachabilityGraph.cpp
Labels: Area: Common libs, Type: bug
