Repository nanoframework/nf-interpreter, pull requests merged in 2019-10, with the labels that each got.

#1450 Correct repo for ChibiOS-Contrib
  CMake/ChibiOS-Contrib.CMakeLists.cmake.in
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build

#1451 Add sanity check to valid image verification
  targets/CMSIS-OS/ChibiOS/common/LaunchCLR.c
Labels: Area: STM32, Type: bug

#1452 Improve sanity check on vector table address
  targets/CMSIS-OS/ChibiOS/common/LaunchCLR.c
Labels: Area: STM32, Type: enhancement

#1454 Add option to build without complex math functions
  src/CLR/System.Math/nf_native_system_math_System_Math.cpp
Labels: Area: Common libs, Type: enhancement

#1456 Update mscorlib assembly declaration
  src/CLR/CorLib/corlib_native.cpp
Labels: Area: Common libs, Type: dependencies

#1457 Improve valid image check to account for ITCM access devices
  targets/CMSIS-OS/ChibiOS/common/LaunchCLR.c
Labels: Area: STM32, Type: bug

#1459 Add support for new ResourceManager class lib
  CMake/Modules/FindNF_CoreCLR.cmake
  CMake/Modules/FindnanoFramework.ResourceManager.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  azure-pipelines.yml
  cmake-variants.TEMPLATE-ESP32.json
  cmake-variants.TEMPLATE.json
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/CorLib/CorLib.vcxproj.filters
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.h
  src/nanoFramework.ResourceManager/nf_system_resourcemanager_System_Resources_ResourceManager.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager_nanoFramework_Runtime_Native_ResourceUtility.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Native_ResourceUtility.cpp
Labels: Area: Common libs, Type: enhancement

#1460 Fix support for SRAM
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL_Power.c
Labels: Area: STM32, Type: bug

#1462 Fix for GetStorageFilesNative when using SPIFFS
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
Labels: Area: STM32, Type: bug

#1463 Update of ESP32 to IDF 3.3 (LTS)
  CMake/Modules/FindBuildUtils.cmake
  CMake/toolchain.FreeRtos.ESP32.GCC.cmake
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  VisualStudioDevelopment/README.md
  azure-pipelines-templates/build-esp32.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  install-scripts/install-esp32-idf.ps1
  install-scripts/install-esp32-libs.ps1
  install-scripts/install-esp32-tools.ps1
  sdkconfig
  src/DeviceInterfaces/Networking.Sntp/nf_networking_sntp.h
  src/PAL/Lwip/lwIP_Sockets.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CopyLibs.cmd
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/IDF/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/IDF/partitions_nanoclr_16mb.csv
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/IDF/partitions_nanoclr_4mb.csv
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/IDF/partitions_nanoclr_8mb.csv
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/esp32_os.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/targetHAL_Time.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/lwipopts.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/nf_api_msg.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/nf_sockets.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/nf_sys_arch.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/targetHAL_Network.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/esp32.project.ld
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/esp32_out.ld
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/target_board.h.in
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/sdkconfig.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/sdkconfig.txt
Labels: Area: ESP32, Area: Interpreter

#1464 Fix terminators on NFReleaseInfo strings
  src/CLR/Debugger/Debugger_stub.cpp
Labels: Area: Interpreter, Type: bug

#1465 Fix time accuracy
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL_Time.cpp
Labels: Area: ESP32, Type: bug

#1466 Enable support for multiple block storage devices
  src/CLR/Debugger/Debugger.cpp
  src/PAL/BlockStorage/nanoPAL_BlockStorage.c
  src/PAL/Include/nanoPAL_BlockStorage.h
Labels: Area: Common libs, Type: enhancement

#1469 Fix STM32 flash driver for L0 series
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv3/flash_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv3/flash_lld.h
Labels: Area: STM32, Type: bug

#1470 Update mbedTLS to v2.16.3
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS_ESP32/CMakeLists.txt
Labels: Area: ESP32, Area: STM32, Type: dependencies

#1471 Fix CRC driver for STM32L0 series
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.h
Labels: Area: STM32, Type: bug
