Repository nanoframework/nf-interpreter, pull requests merged in 2020-04, with the labels that each got.

#1598 Work on GPIO code
  src/PAL/Include/CPU_GPIO_decl.h
  src/Windows.Devices.Gpio/win_dev_gpio_native.h
  src/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioController.cpp
  src/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioController.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioController.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioController.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/os/win32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native.cpp
Labels: Area: Common libs, Area: NXP, Area: STM32, Area: TI-CC13x2_26x2, Area: WIN32, Type: bug

#1599 Cleanup and tidy up code formating
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
Labels: Area: Config-and-Build

#1601 CMake: Clean up message
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build

#1600 Fix STM32F769I clock settings
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
Labels: Area: STM32, Type: bug

#1603 ESP32_WROOM_32: Correcting logical dependency
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
Labels: Area: Config-and-Build

#1604 Update I2C assembly declaration
  src/Windows.Devices.I2c/win_dev_i2c_native.cpp
  src/Windows.Devices.I2c/win_dev_i2c_native.h
Labels: Type: dependencies

#1605 Bulk update dependencies
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/System.Math/nf_native_system_math.cpp
  src/DeviceInterfaces/Networking.Sntp/nf_networking_sntp.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/System.Devices.Dac/sys_dev_dac_native.cpp
  src/System.Devices.Dac/sys_dev_dac_native.h
  src/Windows.Devices.Adc/win_dev_adc_native.cpp
  src/Windows.Devices.Adc/win_dev_adc_native.h
  src/Windows.Devices.Gpio/win_dev_gpio_native.cpp
  src/Windows.Devices.Pwm/win_dev_pwm_native.cpp
  src/Windows.Devices.Pwm/win_dev_pwm_native.h
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.h
  src/Windows.Devices.Spi/win_dev_spi_native.cpp
  src/Windows.Devices.Spi/win_dev_spi_native.h
  src/Windows.Devices.Wifi/win_dev_wifi_native.h
  src/Windows.Storage/win_storage_native.cpp
  src/Windows.Storage/win_storage_native.h
  src/nanoFramework.Devices.Can/nf_devices_can_native.h
  src/nanoFramework.Devices.OneWire/nf_devices_onewire_native.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.h
  src/nanoFramework.Runtime.Events/nf_rt_events_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.System.Collections/nf_system_collections.h
  src/nanoFramework.System.Text/nf_system_text.cpp
  src/nanoFramework.System.Text/nf_system_text.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.h
Labels: Type: dependencies

#1606 Replace call to serial stream with channel equivalent that has timeout
  targets/CMSIS-OS/ChibiOS/common/WireProtocol_HAL_Interface.c
Labels: Area: ChibiOS, Type: bug

#1607 Disable Git-LFS smudge filter for CMSIS repo download
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1608 Remove unused declaration in STM32 flash driver
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv1/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_flash/hal_stm32_flash.c
Labels: Area: STM32, Type: enhancement

#1609 Fix attributes constructor in FieldInfo
  src/CLR/CorLib/corlib_native_System_Reflection_FieldInfo.cpp
Labels: Area: Interpreter, Type: bug

#1610 Increase flash region in debug config
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/common/Device_BlockStorage-DEBUG.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/STM32F091xC_booter-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/STM32F091xC_CLR-DEBUG.ld
Labels: Area: STM32, Type: enhancement

#1612 Double interrupt lock with GPIO
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Area: STM32, Type: bug

#1611 Add support for custom attributes with constructors for classes and methods
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Reflection_FieldInfo.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_RuntimeMethodInfo.cpp
  src/CLR/CorLib/corlib_native_System_RuntimeType.cpp
Labels: Area: Common libs, Type: enhancement

#1613 Remove unused parameter from BringExecCounterToDate
  src/CLR/Core/Execution.cpp
  src/CLR/Core/Thread.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Area: Interpreter, Type: enhancement

#1614 Fix IL instruction isinst
  src/CLR/CorLib/corlib_native_System_Type.cpp
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Array.cpp
  src/CLR/Core/Execution.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Area: Interpreter, Type: bug

#1615 Fix float point comparisons
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/PAL/Double/nanoPAL_NativeDouble.cpp
  src/PAL/Include/nanoPAL_NativeDouble.h
Labels: Area: Interpreter, Type: bug

#1616 Work GpioChangeCounter
  src/Windows.Devices.Gpio/win_dev_gpio_native.cpp
  src/Windows.Devices.Gpio/win_dev_gpio_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioChangeCounter.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioChangeCounter.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioChangeCounter.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioChangeCounter.cpp
Labels: Area: Common libs, Type: bug

#1617 Fix fatFS install command when spaces in path
  CMake/FatFS.CMakeLists.cmake.in
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build

#1618 Fix build version to match published files
  azure-pipelines-templates/build-chibios-stm32.yml
  azure-pipelines-templates/build-esp32.yml
  azure-pipelines-templates/build-freertos-nxp.yml
  azure-pipelines-templates/build-ti-simplelink.yml
  azure-pipelines-templates/nb-gitversioning.yml
Labels: Area: Config-and-Build

#1619 Fix race condition with debugger on soft reboot
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Messaging/Messaging.cpp
Labels: Area: Common libs, Type: bug

#1620 Fix just a few typos
  src/CLR/Core/Execution.cpp
  src/CLR/Include/nanoWeak.h
  src/CLR/Startup/CLRStartup.cpp
  src/CLR/WireProtocol/WireProtocol_Message.c
  src/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/CMSIS-OS/ChibiOS/common/WireProtocol_HAL_Interface.c
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Time.cpp
Labels: Type: documentation
