Repository nanoframework/nf-interpreter, pull requests merged in 2020-06, with the labels that each got.

#1651 Update Runtime.Native assembly
  CMake/Modules/FindNF_CoreCLR.cmake
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Native_GC.cpp
Labels: Type: dependencies

#1652 Work wireless config ESP32
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_NetworkInformation_Wireless80211Configuration.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_NetworkInformation_WirelessAPConfiguration.cpp
  src/HAL/Include/nanoHAL_Network.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Target_Network.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL_ConfigurationManager.cpp
Labels: Breaking-change, Type: bug

#1654 Add ORGPAL3 target
  README.md
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/README.md
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/board.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/board.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/Device_BlockStorage-DEBUG.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/Device_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/targetHAL_ConfigurationManager.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/usbcfg.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/usbcfg.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/ffconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/lwipopts.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/managed_helpers/ORGPAL_PALTHREE.Adc.cs
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/managed_helpers/README.md
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/managed_helpers/package.nuspec
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/mbedtls_config.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/STM32F76xx_booter-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/STM32F76xx_booter.ld
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/chconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/halconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/STM32F76xx_CLR-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/STM32F76xx_CLR.ld
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/chconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/halconf_community.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/mcuconf_community.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/nanoHAL.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/spiffs_config.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/stm32f7xx_hal_conf.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_BlockStorage.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_common.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_external_memory.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_lwip_sntp_opts.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_nf_devices_onewire_config.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_spiffs.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_spiffs.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_system_devices_dac_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_devices_adc_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_windows_storage_config.h
Labels: Type: enhancement

#1645 Rework ESP32 serial implementation
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/Esp32_DeviceMapping.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/Esp32_DeviceMapping.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
Labels: Area: ESP32, Type: bug

#1660 Improve GPIO events for ESP32
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Type: bug, Type: enhancement

#1661 ESP32 Serial fix
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Area: ESP32, Type: bug

#1664 Update ninja build version to latest release
  install-scripts/install-ninja.ps1
Labels: Area: Config-and-Build, Type: enhancement

#1665 Add code style check on PR using Azure Pipelines
  azure-pipelines-templates/check-code-style.yml
  azure-pipelines-templates/download-install-llvm.yml
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/common/Target_Network.cpp
Labels: Area: Config-and-Build

#1658 Rework ESP32 serial update
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/Esp32_DeviceMapping.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/Esp32_DeviceMapping.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
Labels: Type: bug, Type: enhancement

#1667 Update GNU Arm Embedded Toolchain to 9-2020-q2-update
  azure-pipelines-templates/download-hexdfu.yml
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines-templates/download-install-ninja.yml
  azure-pipelines-templates/download-srecord.yml
  azure-pipelines.yml
  install-scripts/install-arm-gcc-toolchain.ps1
Labels: Area: Config-and-Build
