Repository nanoframework/nf-interpreter, pull requests merged in 2020-07, with the labels that each got.

#1670 Work CD-CI
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines-templates/download-srecord.yml
  install-scripts/install-esp32-idf.ps1
  install-scripts/install-esp32-toolchain.ps1
Labels: Area: Config-and-Build

#1669 Fix ChibiOS vectors section alignment
  targets/CMSIS-OS/ChibiOS/common/rules_code.ld
Labels: Area: ChibiOS, Type: bug

#1671 Minor tweaks on targets launch config and cmake variants
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/launch.json
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/launch.json
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/launch.json
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/launch.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/launch.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/launch.json
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/launch.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/launch.json
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/launch.json
Labels: Area: Targets, Type: enhancement

#1672 Update mbedTLS to 2.23.0
  CMake/Modules/FindmbedTLS.cmake
  src/PAL/COM/sockets/ssl/mbedTLS/nf_mbedtls_config.h
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS_ESP32/CMakeLists.txt
Labels: Type: dependencies

#1673 Add native support for ESP32 RMT
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindnanoFramework.Hardware.Esp32.Rmt.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  azure-pipelines.yml
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_TransmitterChannel.cpp
Labels: Area: Config-and-Build, Area: ESP32, Type: enhancement

#1674 Fix inclusion of Interop assemblies through CMake build option
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/NF_NativeAssemblies.cmake
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
Labels: Area: Config-and-Build, Breaking-change

#1675 Update mbedTLS config
  src/PAL/COM/sockets/ssl/mbedTLS/nf_mbedtls_config.h
Labels: Area: Common libs, Type: bug

#1676 Improve code for SPI NativeInit
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
Labels: Type: enhancement

#1677 Improve HAL Initialize/Uninitialize
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_target.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_target.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_target.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.Can/nf_devices_can_native_target.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_target.h
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_target.h
  targets/TI-SimpleLink/nanoCLR/targetHAL.cpp
  targets/TI-SimpleLink/nanoCLR/target_platform.h.in
Labels: Area: FreeRTOS, Area: STM32, Area: TI-CC32xx, Area: TI-SimpleLink, Type: bug

#1678 Fix CMake download path
  install-scripts/install-cmake.ps1
Labels: Area: Config-and-Build

#1679 Fix json format on tasks template
  .vscode/tasks.TEMPLATE.json
Labels: Type: bug

#1680 Fix target name ORGPAL_PALTHREE on cmake-variants
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
Labels: Type: bug

#1681 Various fixes in install scripts
  install-scripts/Initialize-VSCode.ps1
  install-scripts/install-arm-gcc-toolchain.ps1
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
Labels: Type: bug

#1682 Update hint path for gcc in ESP32 toolchain file
  CMake/toolchain.xtensa-esp32-elf.cmake
  CMakeSettings.SAMPLE.json
  azure-pipelines.yml
Labels: Area: Config-and-Build, Breaking-change

#1683 ESP32 Serial Native-store hang fix
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
Labels: Area: ESP32, Status: under review, Type: bug
