Repository nanoframework/nf-interpreter, pull requests merged in 2020-03, with the labels that each got.

#1566 Fix time conversion issues in PAL events
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Events.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Time.cpp
Labels: Area: ChibiOS, Type: bug

#1567 Fix issues with wrong context switching and global lock calls
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.cpp
  src/PAL/AsyncProcCall/AsyncContinuations.cpp
  targets/CMSIS-OS/ChibiOS/Include/targetHAL.h
  targets/CMSIS-OS/ChibiOS/Lwip/platform_sys_arch.c
  targets/CMSIS-OS/ChibiOS/common/Target_Windows_Storage.c
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Events.cpp
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/RNGv1/rng_lld.c
Labels: Area: ChibiOS, Area: Common libs, Type: bug

#1570 Add TARGETINFOSTRING
  CMake/ChibiOS_target_os.h.in
  CMake/ESP32_target_os.h.in
  CMake/FreeRTOS_target_os.h.in
  CMake/TI_SimpleLink_target_os.h.in
  src/CLR/Include/WireProtocol.h
  src/HAL/nanoHAL_SystemInformation.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/target_board.h.in
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoCLR/target_board.h.in
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/target_board.h.in
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_common.h.in
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_common.h.in
Labels: Area: Common libs, Area: Config-and-Build, Area: Targets, Breaking-change

#1572 [network] fix wrong get socket error method
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
Labels: Area: Common libs, Type: bug

#1574 Improve GNU GCC toolchain download
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
Labels: Area: Config-and-Build

#1575 Update AccessMemoryErrorCodes enum
  src/CLR/Debugger/Debugger.h
Labels: Area: Common libs, Breaking-change

#1576 Rework CLR Debug class
  src/CLR/Core/Core.cpp
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Debugger/Debugger.vcxproj
  src/CLR/Debugger/Debugger_full.cpp
  src/CLR/Debugger/Debugger_stub.cpp
  src/CLR/Diagnostics/Info.cpp
  src/CLR/Include/nanoCLR_Debugging.h
  src/CLR/Startup/CLRStartup.cpp
  targets/os/win32/nanoCLR/Generated/CLR_RT_InteropAssembliesTable.cpp
  targets/os/win32/nanoCLR/PAL/blockstorageList_stubs.cpp
  targets/os/win32/nanoCLR/Various.cpp
  targets/os/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Common libs, Type: enhancement

#1577 Simplified timeout handling on flash driver v2
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.c
Labels: Area: STM32, Type: enhancement

#1578 Work on GCC optimizations
  CMake/Modules/CHIBIOS_STM32F0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_GCC_options.cmake
  CMake/binutils.ChibiOS.cmake
Labels: Area: Config-and-Build, Area: STM32

#1579 Work SWO handlers
  targets/CMSIS-OS/common/swo.cpp
Labels: Area: STM32, Type: enhancement

#1429 Implement working GetCustomAttributes
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Reflection_FieldInfo.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_RuntimeMethodInfo.cpp
  src/CLR/CorLib/corlib_native_System_RuntimeType.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Area: Common libs, Status: DONE, Type: enhancement

#1580 Update all assemblies declaration
  src/CLR/System.Math/nf_native_system_math.cpp
  src/DeviceInterfaces/Networking.Sntp/nf_networking_sntp.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/DeviceInterfaces/System.Net/sys_net_native_System_Security_Cryptography_X509Certificates_X509Certificate.cpp
  src/System.Devices.Dac/sys_dev_dac_native.cpp
  src/Windows.Devices.Adc/win_dev_adc_native.cpp
  src/Windows.Devices.Gpio/win_dev_gpio_native.cpp
  src/Windows.Devices.I2c/win_dev_i2c_native.cpp
  src/Windows.Devices.Pwm/win_dev_pwm_native.cpp
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.cpp
  src/Windows.Devices.Spi/win_dev_spi_native.cpp
  src/Windows.Devices.Wifi/win_dev_wifi_native.cpp
  src/Windows.Storage/win_storage_native.cpp
  src/nanoFramework.Devices.Can/nf_devices_can_native.cpp
  src/nanoFramework.Devices.OneWire/nf_devices_onewire_native.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager.h
  src/nanoFramework.ResourceManager/nf_system_resourcemanager_System_Resources_ResourceManager.cpp
  src/nanoFramework.ResourceManager/nf_system_resourcemanager_nanoFramework_Runtime_Native_ResourceUtility.cpp
  src/nanoFramework.Runtime.Events/nf_rt_events_native.cpp
  src/nanoFramework.Runtime.Events/nf_rt_events_native.h
  src/nanoFramework.Runtime.Events/nf_rt_events_native_nanoFramework_Runtime_Events_WeakDelegate.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.System.Collections/nf_system_collections.cpp
  src/nanoFramework.System.Collections/nf_system_collections.h
  src/nanoFramework.System.Collections/nf_system_collections_System_Collections_Queue.cpp
  src/nanoFramework.System.Text/nf_system_text.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native_nanoFramework_Hardware_Stm32_RTC.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.cpp
Labels: Type: dependencies

#1581 Fix events and timer compare
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Time.cpp
  targets/FreeRTOS/common/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS/common/nanoCLR/targetPAL_Time.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetPAL_Time.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Events.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Time.cpp
Labels: Area: ESP32, Area: NXP, Area: STM32, Area: TI-CC13x2_26x2, Type: bug

#1582 Disable optimization on CRC32 calculation
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.c
Labels: Area: STM32, Type: bug

#1583 Fix reboot on idle
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetPAL_Events.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Events.cpp
Labels: Area: Targets, Type: bug

#1584 Improvements in CRC32 calculation
  src/CLR/Core/nanoSupport_CRC32.c
  src/CLR/Include/nanoSupport.h
  targets/CMSIS-OS/ChibiOS/common/nanoSupport_CRC32.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/stm32_crc/hal_stm32_crc.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_crc/hal_stm32_crc.c
  targets/TI-SimpleLink/common/nanoSupport_CRC32.c
  targets/os/win32/nanoCLR/Various.cpp
Labels: Area: Common libs, Area: STM32, Area: TI-SimpleLink, Type: enhancement

#1585 Fix STM32 CRC32 driver
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.c
Labels: Area: STM32, Type: bug

#1586 Improve UpdateConfig command
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_CertificateManager.cpp
  src/HAL/Include/nanoHAL_ConfigurationManager.h
  targets/CMSIS-OS/ChibiOS/common/targetHAL_ConfigurationManager.cpp
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/common/targetHAL_ConfigurationManager.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL_ConfigurationManager.cpp
  targets/TI-SimpleLink/common/targetHAL_ConfigurationManager_CC13x2_26x2.cpp
  targets/TI-SimpleLink/common/targetHAL_ConfigurationManager_CC32xx.cpp
  targets/os/win32/nanoCLR/Various.cpp
Labels: Area: Common libs, Area: ESP32, Area: NXP, Area: STM32, Area: TI-CC13x2_26x2, Breaking-change

#1587 Fix declaration of Windows.Devices.SerialCommunication
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.cpp
Labels: Type: dependencies

#1588 Update Native.Events assembly declaration
  src/nanoFramework.Runtime.Events/nf_rt_events_native.cpp
Labels: Type: dependencies

#1589 Update assembly declarations
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
  src/Windows.Devices.Gpio/win_dev_gpio_native.cpp
  src/Windows.Devices.Wifi/win_dev_wifi_native.cpp
  src/nanoFramework.Devices.Can/nf_devices_can_native.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
Labels: Type: dependencies

#1590 Update install-esp32-tools.ps1
  install-scripts/install-esp32-tools.ps1
Labels: Area: Config-and-Build

#1571 Add Quail storage capability
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/board.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/ffconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_storage_config.h
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/CMakeLists.txt
Labels: Area: STM32, Type: enhancement

#1594 Update declaration of System.Collections
  src/nanoFramework.System.Collections/nf_system_collections.cpp
Labels: Type: dependencies

#1591 Support for microSD Click board.
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/board.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/board.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_storage_config.h
Labels: Area: STM32, Type: enhancement

#1592 Fix deploying for NXP board
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoCLR/main.c
  targets/FreeRTOS/NXP/common/Target_BlockStorage_iMXRTFlashDriver.c
  targets/FreeRTOS/NXP/common/utilities/flexspi_nor_flash_ops.c
  targets/FreeRTOS/NXP/common/utilities/flexspi_nor_flash_ops.h
Labels: Area: NXP, Type: bug

#1593 Update FreeRTOS
  CMake/Modules/FindFreeRTOS.cmake
  CMake/Modules/FreeRTOS_iMXRT10xx_sources.cmake
  azure-pipelines.yml
  targets/FreeRTOS/CMakeLists.txt
Labels: Area: Config-and-Build, Area: FreeRTOS, Type: dependencies

#1596 Fix bug with attribute parser
  src/CLR/Core/TypeSystem.cpp
Labels: Area: Common libs, Type: bug

#1573 Fix unlinking allocated GPIOs.
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Area: STM32, Type: bug

#1595 Fix access to DateTime fields in Windows.Storage
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_target.h
Labels: Area: NXP, Type: bug
