Repository nanoframework/nf-interpreter, pull requests merged in 2020-11, with the labels that each got.

#1754 Fix Read/Write in System.Device.I2c
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/TI-SimpleLink/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
Labels: Area: Common libs, Type: bug

#1755 Work on CMake
  CMake/Modules/NF_Utils.cmake
  CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS_ESP32/CMakeLists.txt
  targets/TI-SimpleLink/CMakeLists.txt
Labels: Area: Config-and-Build

#1756 Update capabilities flags
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/nanoCLR_Debugging.h
Labels: Breaking-change, Type: enhancement

#1757 Update Reboot option flags
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/Include/nanoCLR_Debugging.h
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
Labels: Type: enhancement

#1758 Improvements in target/platform capabilities
  CMake/Modules/FindnanoHALCore.cmake
  src/HAL/Include/nanoHAL_Capabilites.h
  src/HAL/Include/nanoHAL_v2.h
  src/HAL/nanoHAL_Capabilites.c
  targets/CMSIS-OS/ChibiOS/Include/platform_target_capabilities.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_common.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_common.c
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_common.c
  targets/CMSIS-OS/ChibiOS/common/targetHAL.c
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/CMakeLists.txt
  targets/FreeRTOS/common/targetHAL.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/targetHAL.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/CMakeLists.txt
  targets/TI-SimpleLink/common/platformHAL.c
Labels: Area: Config-and-Build, Area: Targets, Type: enhancement

#1759 Work on capability flags
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol.h
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/Include/nanoCLR_Debugging.h
  src/HAL/Include/nanoHAL_Capabilites.h
  src/HAL/nanoHAL_Capabilites.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_common.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_common.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_common.c
  targets/CMSIS-OS/ChibiOS/common/targetHAL.c
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/common/targetHAL.c
  targets/TI-SimpleLink/common/platformHAL.c
  targets/os/win32/Include/targetHAL.h
Labels: Area: Common libs, Area: Targets, Breaking-change, Type: enhancement

#1763 Improvements in CMake
  CMake/binutils.TI_SimpleLink.cmake
  CMakeLists.txt
  build.ps1
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
Labels: Area: Config-and-Build

#1765 Fix reboot options
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/Include/nanoCLR_Debugging.h
Labels: Area: Common libs, Type: bug

#1766 Add nanoBooter flag to ping flags
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol.h
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
Labels: Area: Common libs, Type: enhancement

#1768 Move and clean-up declarations for NATIVE_PROFILE_PAL
  src/HAL/Include/nanoHAL.h
  src/PAL/Include/nanoPAL_AsyncProcCalls_decl.h
  src/PAL/Include/nanoPAL_Events.h
Labels: Area: Config-and-Build

#1767 Fix several missing or wrong defines in ChibiOS overlay
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/stm32_fsmc/hal_stm32_fsmc.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv1/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv3/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FSMCv1/fsmc_nand_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FSMCv1/fsmc_nand_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_fsmc/hal_stm32_fsmc.c
Labels: Area: Config-and-Build

#1769 Add compiler warning to improve builds
  CMake/Modules/CHIBIOS_STM32F0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/FreeRTOS_iMXRT10xx_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC13x2_26x2_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_GCC_options.cmake
  CMake/toolchain.xtensa-esp32-elf.cmake
Labels: Area: Config-and-Build

#1770 Revert warning in ESP32 build
  CMake/toolchain.xtensa-esp32-elf.cmake
Labels: Area: Config-and-Build

#1772 Move NANOCLR_GRAPHICS to target platform template
  src/HAL/Include/nanoHAL_Graphics.h
  src/nanoFramework.ResourceManager/nf_system_resourcemanager_System_Resources_ResourceManager.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/target_board.h.in
Labels: Area: Config-and-Build

#1774 Fix CMakes for ST Cube packages
  CMake/Modules/CHIBIOS_STM32F7xx_sources.cmake
  CMake/Modules/FindSTM32F0_CubePackage.cmake
  CMake/Modules/FindSTM32F4_CubePackage.cmake
  CMake/Modules/FindSTM32F7_CubePackage.cmake
  CMake/Modules/STM32_CubePackage.cmake
Labels: Area: Config-and-Build

#1775 Extract platform dependencies in CMakes
  CMake/Modules/FindSTM32F7_CubePackage.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/stm32f7xx_hal_conf.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeLists.txt
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
Labels: Area: Config-and-Build

#1776 Fix bootloader config for F769
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_common.c
Labels: Area: STM32, Type: bug

#1777 Fix CMakes for ST Cube packages (H7)
  CMake/Modules/FindSTM32H7_CubePackage.cmake
Labels: Area: Config-and-Build

#1778 Work CI-CD
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
Labels: Area: Config-and-Build

#1779 Clean-up lwIP for ChibiOS targets
  CMake/Modules/FindCHIBIOS_LWIP.cmake
Labels: Area: Config-and-Build

#1782 fix-h7-cmake-sources
  CMake/Modules/CHIBIOS_STM32H7xx_sources.cmake
Labels: Area: Config-and-Build

#1781 Fix order of boot flags check
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
Labels: Area: NXP, Area: STM32, Type: bug

#1783 Add build parameter TARGET_SERIAL_BAUDRATE
  .vscode/cmake-variants.TEMPLATE.json
  .vscode/tasks.TEMPLATE.json
  CMake/ESP32_target_os.h.in
  CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/WireProtocol_HAL_Interface.c
Labels: Area: Config-and-Build

#1784 Rename flash driver structure
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/include/stm32_flash/hal_stm32_flash.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv1/flash_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv1/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv3/flash_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv3/flash_lld.h
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/src/stm32_flash/hal_stm32_flash.c
Labels: Area: ChibiOS, Type: enhancement

#1790 Remove unused source files
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/WireProtocol_App_Interface.c
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/WireProtocol_MonitorCommands.c
Labels: Area: Config-and-Build

#1789 Add Monitor_TargetInfo command
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Debugger/Debugger_full.cpp
  src/CLR/Debugger/Debugger_minimal.cpp
  src/CLR/Debugger/Debugger_stub.cpp
  src/CLR/Include/WireProtocol.h
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/Include/nanoCLR_Debugging.h
  src/CLR/WireProtocol/WireProtocol.vcxproj
  src/CLR/WireProtocol/WireProtocol_MonitorCommands.c
  src/HAL/Include/nanoHAL_ReleaseInfo.h
  src/HAL/nanoHAL_SystemInformation.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/Device_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/mbn_quail_booter.ld
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/mbn_quail_CLR.ld
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_App_Interface.c
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_App_Interface.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
  targets/os/win32/Include/target_board.h
  targets/os/win32/nanoCLR.sln
Labels: Type: enhancement

#1786 Update config to use VS2019 image in Azure builds
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1787 Makes RTOS version parameter generic
  CMake/FreeRTOS_target_os.h.in
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/README.md
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/cmake-variants.json
Labels: Area: Config-and-Build

#1785 Removes the MBN Quail target as a reference board.
  README.md
  README.zh-cn.md
  azure-pipelines.yml
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/README.md
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/board.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/board.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/Device_BlockStorage-DEBUG.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/Device_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/usbcfg.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/common/usbcfg.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/ffconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/launch.json
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/chconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/halconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/mbn_quail_booter-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/mbn_quail_booter.ld
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/mcuconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/chconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/halconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/halconf_nf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/mbn_quail_CLR-DEBUG.ld
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/mbn_quail_CLR.ld
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/mcuconf_nf.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/nanoHAL.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_BlockStorage.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_BlockStorage.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_common.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_common.h.in
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_nf_devices_onewire_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_nf_devices_onewire_config.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_system_devices_dac_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_serialcommunication_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_serialcommunication_config.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_storage_config.h
Labels: Area: Config-and-Build

#1788 Display Flush fix plus extra SPI displays
  src/nanoFramework.Graphics/Graphics/Displays/Display.h
  src/nanoFramework.Graphics/Graphics/Displays/DisplayInterface.h
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Otm8009a_DSI_Video_Mode.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1306_128x64.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1331_94x64_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/nanoFramework.Graphics/DSI_To_Display_Video_Mode.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/app_main.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL.cpp
Labels: Type: bug, Type: enhancement

#1791 Rework WP commands
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/WireProtocol/WireProtocol_MonitorCommands.c
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
  targets/os/win32/nanoCLR/Various.cpp
Labels: Area: ChibiOS, Area: Common libs, Area: FreeRTOS, Type: enhancement

#1793 Add TARGET_NAME build option
  .vscode/cmake-variants.TEMPLATE.json
  CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/target_board.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_common.h.in
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoBooter/target_board.h.in
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/nanoCLR/target_board.h.in
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/target_common.h.in
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_common.h.in
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_common.h.in
Labels: Area: Config-and-Build

#1794 Add new target ESP32_PICO
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1797 Support multiple variants choice per target variant file
  install-scripts/Set-VSCode-CMakes.ps1
Labels: Area: Config-and-Build
