Repository nanoframework/nf-interpreter, pull requests merged in 2020-10, with the labels that each got.

#1707 Update checksum to match RMT assembly
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.cpp
Labels: Type: bug

#1708 Update RMT interface so its now correct
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.cpp
Labels: Area: ESP32, Type: bug

#1709 Fix nanoHAL_Uninitialize for TI SimpleLink
  targets/TI-SimpleLink/nanoCLR/targetHAL.cpp
  targets/TI-SimpleLink/nanoCLR/target_platform.h.in
Labels: Area: TI-SimpleLink, Hacktoberfest, Type: bug

#1710 Rework system state and PAL events
  CMake/Modules/FindNF_CoreCLR.cmake
  src/HAL/Include/nanoHAL_v2.h
  src/HAL/nanoHAL_SystemEvents.c
  src/PAL/Events/nanoPAL_Events.cpp
  src/PAL/Include/nanoPAL_Events.h
  targets/CMSIS-OS/ChibiOS/Include/targetHAL.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetHAL.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS/NXP/nanoCLR/targetHAL.cpp
  targets/FreeRTOS/common/include/targetHAL.h
  targets/FreeRTOS/common/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/targetHAL.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetHAL.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetPAL_Events.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/targetPAL_Events.cpp.groups.cpp
  targets/TI-SimpleLink/Include/targetHAL.h
  targets/TI-SimpleLink/nanoCLR/targetHAL.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Events.cpp
Labels: Area: Common libs, Area: Interpreter, Hacktoberfest, Type: enhancement

#1712 Removes duplicate `elseif`
  CMakeLists.txt
Labels: Area: Config-and-Build

#1715 Fix PAL events getter
  src/PAL/Events/nanoPAL_Events.cpp
Labels: Type: bug

#1714 Move events from CLR_RT_ExecutionEngine to a separate enum
  src/CLR/CorLib/corlib_native_System_AppDomain.cpp
  src/CLR/Core/Execution.cpp
  src/CLR/Core/Hardware/Hardware.cpp
  src/CLR/Include/nanoCLR_Runtime.h
  src/CLR/Messaging/Messaging.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_SslNative.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
  src/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Networking.Sockets/win_net_sockets_native_Windows_Networking_Sockets_SocketNative.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_FileIO.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/nanoFramework.Devices.OneWire/nf_devices_onewire_native_nanoFramework_Devices_OneWire_OneWireController.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_FileIO.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Networking.Sockets/win_net_sockets_native_Windows_Networking_Sockets_SocketNative.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_FileIO.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink_nanoFramework_TI_EasyLink_EasyLinkController.cpp
Labels: Area: Common libs, Area: Interpreter, Hacktoberfest, Type: enhancement

#1713 Remove MBEDOS
  CMake/Modules/FindMBEDOS.cmake
  CMake/Modules/JSONParser.cmake
  CMake/Modules/MBED_STM32F0_GCC_options.cmake
  CMake/Modules/MBED_STM32F0_sources.cmake
  CMake/Modules/MBED_STM_sources.cmake
  CMake/mBedOS.CMakeLists.cmake.in
Labels: Area: Config-and-Build, Hacktoberfest

#1717 Simplifies naming convention for RTOS Source location.
  .vscode/cmake-variants.TEMPLATE.json
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/FreeRTOS/CMakeLists.txt
Labels: Area: Config-and-Build, Hacktoberfest

#1719 Simplifies naming convention for RTOS version tag
  .vscode/cmake-variants.TEMPLATE.json
  CMake/ChibiOS.CMakeLists.cmake.in
  CMake/FreeRTOS.CMakeLists.cmake.in
  CMake/RTXRTOS.CMakeLists.cmake.in
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
Labels: Area: Config-and-Build

#1718 Bring DAC native layer inline with managed
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindSystem.Device.Dac.cmake
  CMake/Modules/FindSystem.Devices.Dac.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  CMakeLists.txt
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  azure-pipelines.yml
  build.ps1
  src/System.Device.Dac/sys_dev_dac_native.cpp
  src/System.Device.Dac/sys_dev_dac_native.h
  src/System.Devices.Dac/sys_dev_dac_native.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_system_device_dac_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_system_device_dac_config.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.Dac/sys_dev_dac_native_System_Device_Dac_DacChannel.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.Dac/sys_dev_dac_native_System_Device_Dac_DacController.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.Dac/sys_dev_dac_native_target.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.Dac/sys_dev_dac_native_System_Device_Dac_DacChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.Dac/sys_dev_dac_native_System_Device_Dac_DacController.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.Dac/sys_dev_dac_native_target.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Devices.Dac/sys_dev_dac_native_System_Devices_Dac_DacChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Devices.Dac/sys_dev_dac_native_System_Devices_Dac_DacController.cpp
Labels: Area: Common libs, Hacktoberfest, Type: enhancement

#1720 Initial support for STM32L4xx
  CMake/Modules/CHIBIOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_sources.cmake
  CMake/Modules/FindCHIBIOS.cmake
  CMake/Modules/FindSTM32L4_CubePackage.cmake
Labels: Area: Config-and-Build, Hacktoberfest

#1723 Additional steps for AzureRTOS
  CMake/Modules/FindAzureRTOS.cmake
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/CMakeLists.txt
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/STM32L475VGTx_CLR-DEBUG.ld
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_BlockStorage.c
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_BlockStorage.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_common.h.in
Labels: Area: Config-and-Build

#1724 Fix Timeout.InfiniteTimeSpan
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
Labels: Type: bug, hacktoberfest-accepted

#1725 Work TI SimpleLink
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink_nanoFramework_TI_EasyLink_EasyLinkController.cpp
Labels: Area: TI-CC13x2_26x2, Type: dependencies, Type: enhancement, hacktoberfest-accepted

#1726 Rework TI EasyLink
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.TI.EasyLink/nf_ti_easylink_nanoFramework_TI_EasyLink_EasyLinkController.cpp
Labels: Area: TI-CC13x2_26x2, Type: enhancement, hacktoberfest-accepted

#1727 Adjust configuration of TI_CC1352R1_LAUNCHXL
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/TI_CC1352R1_LAUNCHXL.syscfg
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/common/Device_BlockStorage-DEBUG.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/CC13x2_26x2_CLR-DEBUG.ld
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_common.h.in
Labels: Area: TI-CC13x2_26x2, Type: enhancement, hacktoberfest-accepted

#1730 Fix ChibiOS Cmake build warnings
  CMake/ChibiOS-Contrib.CMakeLists.cmake.in
  CMake/Modules/CHIBIOS_STM32F0xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_sources.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_sources.cmake
  CMake/Modules/FindCHIBIOS.cmake
  CMake/Modules/FindChibiOS-Contrib.cmake
  CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeLists.txt
Labels: Area: Config-and-Build

#1732 Update Windows.Devices.Spi declaration
  src/Windows.Devices.Spi/win_dev_spi_native.cpp
Labels: Type: dependencies

#1734 Update System.Device.Gpio assembly
  src/System.Device.Gpio/sys_dev_gpio_native.cpp
Labels: Type: dependencies

#1735 Fix the Set-VSCode-CMakes script
  install-scripts/Set-VSCode-CMakes.ps1
Labels: Area: Config-and-Build, hacktoberfest-accepted

#1737 Work CD-CI
  azure-pipelines-templates/build-chibios-stm32.yml
  azure-pipelines-templates/build-esp32.yml
  azure-pipelines-templates/build-freertos-nxp.yml
  azure-pipelines-templates/build-preparations.yml
  azure-pipelines-templates/build-ti-simplelink.yml
  azure-pipelines-templates/pack-publish-artifacts.yml
  azure-pipelines-templates/pack-publish-managed-helpers.yml
  azure-pipelines-templates/pack-publish-ti-sl-managed-helpers.yml
  azure-pipelines-templates/publish-bintray.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build, hacktoberfest-accepted

#1736 Update Azure pipeline to include ESP WROVER KIT with ILI9341
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1738 Update mscorlib declaration
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
Labels: Type: dependencies

#1739 Add native implementation for Enum.HasFlag
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Enum.cpp
Labels: Area: Common libs, Type: enhancement, hacktoberfest-accepted

#1740 Add result check on local variables initialization
  src/CLR/Core/CLR_RT_StackFrame.cpp
Labels: Area: Interpreter, Type: bug, hacktoberfest-accepted

#1741 Fix implementation of WeakReference
  src/CLR/CorLib/corlib_native_System_WeakReference.cpp
  src/CLR/Core/TypeSystemLookup.cpp
Labels: Area: Interpreter, Type: bug, hacktoberfest-accepted

#1742 Update and rework System.Device.Gpio
  src/System.Device.Gpio/sys_dev_gpio_native.cpp
  src/System.Device.Gpio/sys_dev_gpio_native.h
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioController.cpp
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioPin.cpp
Labels: Type: dependencies, Type: enhancement

#1743 Improvements in GPIO code
  src/PAL/Include/CPU_GPIO_decl.h
  src/System.Device.Gpio/sys_dev_gpio_native.cpp
  src/System.Device.Gpio/sys_dev_gpio_native.h
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioPin.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Type: dependencies, Type: enhancement

#1744 Fix Gpio.Toggle for ESP32
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Area: ESP32, Type: bug

#1745 Fix Gpio.Write
  src/System.Device.Gpio/sys_dev_gpio_native.h
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioPin.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Area: Common libs, Area: ESP32, Type: bug

#1746 Fix initialization of network config block
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/common/targetHAL_ConfigurationManager.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/common/targetHAL_ConfigurationManager.cpp
  targets/TI-SimpleLink/common/targetHAL_ConfigurationManager_CC13x2_26x2.cpp
  targets/TI-SimpleLink/common/targetHAL_ConfigurationManager_CC32xx.cpp
Labels: Area: STM32, Area: TI-CC13x2_26x2, Area: TI-CC32xx, Type: bug, hacktoberfest-accepted

#1747 Fix STM32 LLD flash write
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.c
Labels: Area: STM32, Type: bug

#1748 Work configuration block storage
  src/HAL/Include/nanoHAL_ConfigurationManager.h
  src/HAL/nanoHAL_ConfigurationManager.c
  src/HAL/nanoHAL_ConfigurationManager_stubs.c
  targets/CMSIS-OS/ChibiOS/common/targetHAL_ConfigurationManager.cpp
Labels: Area: ChibiOS, Type: bug, Type: enhancement, hacktoberfest-accepted

#1749 Fix AddCaCertificateBundle in Certificate Store
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_CertificateManager.cpp
Labels: Area: Common libs, Type: bug, hacktoberfest-accepted

#1750 Add missing declaration for System.SpanByte
  src/CLR/CorLib/corlib_native.h
Labels: Type: dependencies

#1751 Add native support for System.Device.I2c
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindSystem.Device.I2c.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  CMakeLists.txt
  azure-pipelines.yml
  src/System.Device.I2c/sys_dev_i2c_native.cpp
  src/System.Device.I2c/sys_dev_i2c_native.h
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_system_device_i2c_config.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/System.Device.I2c/sys_dev_i2c_native_target.h
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/cmake-variants.json
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/target_system_device_i2c_config.cpp
  targets/FreeRTOS/NXP/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/System.Device.I2c/sys_dev_i2c_native_target.h
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2c_I2cController.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_target.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.I2c/sys_dev_i2c_native_target.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/target_system_device_i2c_config.cpp
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_sys_device_i2c_config.cpp
  targets/TI-SimpleLink/nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/TI-SimpleLink/nanoCLR/System.Device.I2c/sys_dev_i2c_native_target.h
Labels: Area: Common libs, Area: Config-and-Build, Type: enhancement, hacktoberfest-accepted

#1752 Fix cmake version msgs
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/cmake-variants.json
  targets/TI-SimpleLink/CMakeLists.txt
Labels: Area: Config-and-Build

#1753 Fix socket timeout for sending & receiving
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
Labels: Area: Common libs, Type: bug, hacktoberfest-accepted
