Repository nanoframework/nf-interpreter, pull requests merged in 2020-05, with the labels that each got.

#1621 Work in TI CC3220SF target
  CMake/Modules/FindTI_SimpleLink.cmake
  CMake/Modules/TI_SimpleLink_CC13x2_26x2_sources.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_sources.cmake
  azure-pipelines.yml
  src/DeviceInterfaces/Networking.Sntp/nf_networking_sntp.h
  targets/TI-SimpleLink/CMakeLists.txt
  targets/TI-SimpleLink/Include/CLR_Startup_Thread.h
  targets/TI-SimpleLink/Include/WireProtocol_ReceiverThread.h
  targets/TI-SimpleLink/Include/targetHAL.h
  targets/TI-SimpleLink/Include/targetHAL_Time.h
  targets/TI-SimpleLink/Include/targetSimpleLinkCC32xx_Threads.h
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/Board.h
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/CC3220SF_LAUNCHXL.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/CC3220SF_LAUNCHXL.h
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/FreeRTOSConfig.h
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/common/Device_BlockStorage-DEBUG.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/common/Device_BlockStorage.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/CC3220SF_CLR-DEBUG.ld
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/CC3220SF_CLR.ld
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_BlockStorage.h
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/ti-rtos-debug.cfg
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/ti-rtos-release.cfg
  targets/TI-SimpleLink/common/CMakeLists.txt
  targets/TI-SimpleLink/common/FreeRTOS-openocd.c
  targets/TI-SimpleLink/common/WireProtocol_ReceiverThread.c
  targets/TI-SimpleLink/common/platformHAL_Time.cpp
  targets/TI-SimpleLink/nanoCLR/targetHAL_Time.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Events.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Time.cpp
  targets/TI-SimpleLink/nanoCLR/targetSimpleLinkCC32xx_Sntp.c
  targets/TI-SimpleLink/nanoCLR/targetSimpleLinkCC32xx_Threads.c
Labels: Area: TI-CC32xx, Breaking-change

#1623 Work CD-CI
  CMake/Modules/NF_Utils.cmake
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/FreeRTOS_ESP32/CMakeLists.txt
  targets/TI-SimpleLink/CMakeLists.txt
Labels: Area: Config-and-Build

#1622 Adds a config level for SPI on ChibiOS targets
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/board.c
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/board.h
  targets/CMSIS-OS/ChibiOS/ST_NUCLEO64_F091RC/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_target.h
Labels: Area: ChibiOS, Area: Interpreter, Area: STM32, Type: enhancement

#1624 Work on boot and debugger
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Debugger/Debugger_stub.cpp
  src/CLR/Include/WireProtocol.h
  src/CLR/Include/nanoCLR_Debugging.h
  src/CLR/Startup/CLRStartup.cpp
  targets/os/win32/nanoCLR/CLRStartup.cpp
Labels: Area: Common libs, Breaking-change, Type: enhancement

#1625 Several fixes in CMakes with TI CC32xx SDK
  CMake/Modules/FindTI_SimpleLink.cmake
  targets/TI-SimpleLink/CMakeLists.txt
Labels: Area: Config-and-Build, Area: TI-CC32xx

#1626 Work on TI CC3220SF target
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/common/Device_BlockStorage-DEBUG.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/common/Device_BlockStorage.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/CC3220SF_CLR-DEBUG.ld
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/CC3220SF_CLR.ld
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/ti-rtos-debug.cfg
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/ti-rtos-release.cfg
  targets/TI-SimpleLink/nanoCLR/targetSimpleLinkCC32xx_Threads.c
Labels: Area: TI-CC32xx, Type: enhancement

#1627 Fix CRC32 calculation for CC32xx SDK
  targets/TI-SimpleLink/common/CMakeLists.txt
  targets/TI-SimpleLink/common/nanoSupport_CRC32.c
Labels: Area: TI-CC32xx, Type: bug

#1629 Work on DateTime code
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_DateTime.cpp
Labels: Area: Common libs, Type: enhancement

#1630 Remove verbose switch from CMake expand
  CMake/Modules/FindCHIBIOS_FATFS.cmake
  CMake/Modules/FindCHIBIOS_LWIP.cmake
Labels: Area: Config-and-Build

#1631 Move WriteLine implementation to Runtime.Native
  src/CLR/CorLib/corlib_native_System_Console.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Native_Debug.cpp
Labels: Area: Common libs, Type: enhancement

#1632 Add missing configuration for CS in SPI configuration
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_windows_devices_spi_config.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
Labels: Area: STM32, Type: bug, Type: enhancement

#1633 Fix System.Network declarations
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/PAL/COM/sockets/sockets_lwip.cpp
  src/PAL/Include/nanoPAL_Sockets.h
  src/PAL/Lwip/lwIP_Sockets.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/targetHAL_Network.cpp
  targets/TI-SimpleLink/common/simplelink_sockets.cpp
  targets/TI-SimpleLink/common/simplelink_sockets_functions.cpp
  targets/TI-SimpleLink/common/sockets_simplelink.cpp
Labels: Area: Common libs, Type: bug

#1635 Decrease time to disconnect and reconnect STM32 targets that implement CDC
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/MBN_QUAIL/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/nanoCLR/main.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/main.c
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/main.c
Labels: Area: STM32, Type: enhancement

#1636 Work on SWO
  azure-pipelines.yml
  targets/CMSIS-OS/common/swo.cpp
Labels: Area: STM32, Type: bug

#1634 Support for SPI4 on STM32F429I-DISCOVERY
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F429I_DISCOVERY/target_windows_devices_spi_config.cpp
Labels: Area: STM32, Type: enhancement

#1638 Update Devices.Gpio declaration
  src/PAL/Include/CPU_GPIO_decl.h
  src/Windows.Devices.Gpio/win_dev_gpio_native.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioChangeCounter.cpp
Labels: Area: Common libs, Type: enhancement

#1639 Update SPI declaration
  src/Windows.Devices.Spi/win_dev_spi_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
  targets/os/win32/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
Labels: Area: Common libs, Type: enhancement

#1640 Update SerialCommunication assembly to include enums from managed
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.h
Labels: Area: Common libs, Type: enhancement

#1643 Add SetupTimeoutFromTimeSpan
  src/CLR/Core/CLR_RT_StackFrame.cpp
  src/CLR/Include/nanoCLR_Runtime.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Area: Common libs, Type: enhancement

#1644 Remove c_Flags_Patch from CLR_RECORD_ASSEMBLY
  src/CLR/CorLib/corlib_native_System_AppDomain.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Types.h
Labels: Area: Common libs, Breaking-change, Type: enhancement

#1646 Rework NativeInit for SPI
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Spi/win_dev_spi_native_Windows_Devices_Spi_SpiDevice.cpp
Labels: Area: STM32, Type: bug

#1647 Fix getting DateTime value from boxed object
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_DateTime.cpp
Labels: Area: Common libs, Type: bug

#1650 Update Rutime.Native and mscorlib assemblies
  CMake/Modules/FindNF_CoreCLR.cmake
  src/CLR/CorLib/CorLib-vs2019.vcxproj
  src/CLR/CorLib/CorLib-vs2019.vcxproj.filters
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/CorLib/CorLib.vcxproj.filters
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Console.cpp
  src/CLR/CorLib/corlib_native_System_Diagnostics_Debug.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Native_Debug.cpp
Labels: Type: dependencies
