Repository nanoframework/nf-interpreter, pull requests merged in 2020-08, with the labels that each got.

#1684 Fix create Process failed error on ESP32 build
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
Labels: Type: bug, Type: enhancement

#1685 Rework mbedTLS for ESP32
  CMake/Modules/FindmbedTLS.cmake
  targets/FreeRTOS_ESP32/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
Labels: Area: ESP32, Breaking-change

#1686 Rework sockets definition
  src/PAL/Include/nanoPAL_Network.h
  targets/CMSIS-OS/ChibiOS/Include/lwipopts.h
  targets/CMSIS-OS/ChibiOS/Include/targetHAL.h
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ORGPAL_PALTHREE/target_lwipopts.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_common.h.in
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_lwipopts.h
  targets/FreeRTOS/common/include/lwipopts.h
  targets/FreeRTOS/common/include/targetHAL.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/targetHAL.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/README.md
  targets/os/win32/Include/targetHAL.h
Labels: Area: Config-and-Build

#1687 Update cmake-variants.TEMPLATE.json
  .vscode/cmake-variants.TEMPLATE.json
Labels: Type: enhancement

#1689 Add launch and cmake-variants templates to TI targets
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/launch.json
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/cmake-variants.json
Labels: Type: enhancement

#1688 Fix UART timeouts configuration
  targets/TI-SimpleLink/nanoCLR/targetPAL.c
Labels: Area: TI-CC13x2_26x2, Type: bug

#1690 Increase CLR block size in debug configuration
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/common/Device_BlockStorage-DEBUG.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/CC13x2_26x2_CLR-DEBUG.ld
Labels: Area: TI-CC13x2_26x2, Type: enhancement
