Repository nanoframework/nf-interpreter, pull requests merged in 2020-01, with the labels that each got.

#1535 Fix SWO output
  targets/CMSIS-OS/common/swo.cpp
Labels: Area: STM32, Type: bug

#1536 Fix UpdateConfigurationBlock
  targets/CMSIS-OS/ChibiOS/common/targetHAL_ConfigurationManager.cpp
Labels: Area: STM32, Type: bug

#1537 Update GCC to 2019-Q4-Major
  install-scripts/install-arm-gcc-toolchain.ps1
Labels: Area: Config-and-Build, Type: enhancement

#1538 FatFS fixes for F7 series
  CMake/Modules/FindCHIBIOS_FATFS.cmake
  targets/CMSIS-OS/ChibiOS/FatFS/fatfs_diskio.c
Labels: Area: STM32, Type: bug

#1541 gitmodules: Using relative url and appending ".git"
  .gitmodules
Labels: Area: Config-and-Build

#1539 Seperate FatFS from ChibiOS
  CMake/FatFS.CMakeLists.cmake.in
  CMake/Modules/FindCHIBIOS_FATFS.cmake
  CMake/Modules/FindFATFS.cmake
  CMake/Modules/FindWindows.Storage.cmake
  cmake-variants.TEMPLATE.json
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/NETDUINO3_WIFI/CMakeLists.txt
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
Labels: Area: Config-and-Build
