Repository nanoframework/nf-interpreter, pull requests merged in 2020-09, with the labels that each got.

#1691 Update SDK for CC1352R1
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindnanoFramework.TI.EasyLink.cmake
  CMake/Modules/TI_SimpleLink_CC13x2_26x2_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC13x2_26x2_sources.cmake
  CMake/TI_SysConfig.CMakeLists.cmake.in
  azure-pipelines.yml
  targets/TI-SimpleLink/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/Board.h
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CC1352R1_LAUNCHXL.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CC1352R1_LAUNCHXL.h
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CC1352R1_LAUNCHXL_fxns.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/TI_CC1352R1_LAUNCHXL.syscfg
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/ccfg.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/common/Device_BlockStorage-DEBUG.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/common/Device_BlockStorage.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/easylink/easylink_config.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/easylink_config.h
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/CC13x2_26x2_CLR-DEBUG.ld
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/CC13x2_26x2_CLR.ld
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/smartrf_settings/smartrf_settings.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/smartrf_settings/smartrf_settings.h
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/smartrf_settings/smartrf_settings_predefined.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/smartrf_settings/smartrf_settings_predefined.h
  targets/TI-SimpleLink/common/easylink/EasyLink.c
  targets/TI-SimpleLink/common/easylink/EasyLink.h
  targets/TI-SimpleLink/nanoCLR/targetPAL.c
Labels: Area: Config-and-Build, Breaking-change, Type: dependencies

#1692 Rework CPU GPIO for TI SimpleLink
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/TI_CC1352R1_LAUNCHXL.syscfg
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Type: bug

#1694 Fix output of TI SDK version
  CMake/TI_SimpleLink_target_os.h.in
  targets/TI-SimpleLink/CMakeLists.txt
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_common.h.in
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_common.h.in
Labels: Area: Config-and-Build

#1693 Rework Debugger::AccessMemory
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol_MonitorCommands.h
  src/CLR/Include/nanoCLR_Debugging.h
  targets/CMSIS-OS/ChibiOS/nanoBooter/WireProtocol_MonitorCommands.c
  targets/FreeRTOS/NXP/nanoBooter/WireProtocol_MonitorCommands.c
Labels: Type: enhancement

#1695 Several fixes with lastest CC13x2_26x2 SDK
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/TI_CC1352R1_LAUNCHXL.syscfg
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_common.h.in
  targets/TI-SimpleLink/common/GenericPort.cpp
  targets/TI-SimpleLink/common/WireProtocol_HAL_Interface.c
  targets/TI-SimpleLink/nanoCLR/targetPAL.c
  targets/TI-SimpleLink/nanoCLR/targetPAL_Events.cpp
  targets/TI-SimpleLink/nanoCLR/targetPAL_Time.cpp
Labels: Area: TI-CC13x2_26x2, Type: bug

#1696 Work on CPU GPIO
  src/PAL/Include/CPU_GPIO_decl.h
  src/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Area: Common libs, Area: Targets, Type: bug, Type: enhancement

#1697 Improvements on GPIO layer for TI SimpleLink
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_windows_devices_gpio.h
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/target_windows_devices_gpio.h
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Gpio/win_dev_gpio_native_target.h
Labels: Area: TI-SimpleLink, Type: bug

#1698 Add support for nanoFramework.Hardware.TI assembly
  CMake/Modules/FindnanoFramework.Hardware.TI.cmake
  CMake/Modules/NF_NativeAssemblies.cmake
  azure-pipelines.yml
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native_nanoFramework_Hardware_TI_Power.cpp
  targets/TI-SimpleLink/nanoCLR/targetHAL_Power.c
Labels: Area: TI-CC13x2_26x2, Type: enhancement

#1699 Fix return value from ADC Read
  azure-pipelines.yml
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/TI_CC1352R1_LAUNCHXL.syscfg
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/nanoCLR/main.c
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_windows_devices_adc_config.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
  targets/TI-SimpleLink/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_target.h
Labels: Type: bug

#1700 Add implementation for Hardware.TI.Utilities class
  CMake/Modules/FindnanoFramework.Hardware.TI.cmake
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native_nanoFramework_Hardware_TI_Utilities.cpp
Labels: Area: TI-SimpleLink, Type: enhancement

#1702 Add back LTO optimizations for NXP targets
  CMake/binutils.FreeRTOS.cmake
  targets/FreeRTOS/CMakeLists.txt
Labels: Area: Config-and-Build

#1703 Update Hardware.TI assembly
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.cpp
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native.h
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native_nanoFramework_Hardware_TI_Power.cpp
Labels: Area: TI-CC13x2_26x2, Type: enhancement

#1704 Fix wake-up from standby
  targets/TI-SimpleLink/nanoCLR/nanoFramework.Hardware.TI/nf_hardware_ti_native_nanoFramework_Hardware_TI_Power.cpp
Labels: Area: TI-CC13x2_26x2

#1701 Add RMT receiver to Esp32 RMT module
  CMake/Modules/FindnanoFramework.Hardware.Esp32.Rmt.cmake
  CMakeLists.txt
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_ReceiverChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_RmtChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_TransmitterChannel.cpp
Labels: Area: Config-and-Build, Area: ESP32, Type: dependencies, Type: enhancement

#1706 Update mscorlib declaration
  src/CLR/CorLib/corlib_native.cpp
Labels: Type: dependencies
