Repository nanoframework/nf-interpreter, pull requests merged in 2021-04, with the labels that each got.

#1874 Fix NXP nanoBooter build
  CMake/binutils.FreeRTOS.cmake
  targets/FreeRTOS/_common/hardfault.c
  targets/FreeRTOS/_common/include/TargetHAL_Spi.h
Labels: Area: FreeRTOS, Area: NXP, Type: bug

#1875 Fix potential memory leak in System.IO
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_File.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_FileStream.cpp
Labels: Type: bug

#1876 Update Windows.Devices.Wifi assembly
  src/Windows.Devices.Wifi/win_dev_wifi_native.cpp
  src/Windows.Devices.Wifi/win_dev_wifi_native.h
Labels: Type: dependencies

#1878 Enable DAC for ESP32 targets
  azure-pipelines.yml
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/sdkconfig
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/target_system_device_dac_config.cpp
Labels: Area: Config-and-Build

#1881 Logo link update
  README.md
Labels: Type: dependencies

#1879 Update variants files for DAC support.
  .vscode/cmake-variants-DEVCONTAINER.json
  build.ps1
  src/System.Device.Dac/sys_dev_dac_native.cpp
  targets/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
Labels: Area: Config-and-Build

#1882 Fixes issue #730 (Enum.HasFlag throws ArgumentException)
  src/CLR/CorLib/corlib_native_System_Enum.cpp
Labels: Type: bug

#1884 Rework of WireProtocol
  src/CLR/Include/WireProtocol.h
  src/CLR/Include/WireProtocol_HAL_Interface.h
  src/CLR/Include/WireProtocol_Message.h
  src/CLR/WireProtocol/WireProtocol_HAL_Interface.c
  src/CLR/WireProtocol/WireProtocol_Message.c
  targets/ChibiOS/_common/WireProtocol_HAL_Interface.c
  targets/ChibiOS/_common/WireProtocol_ReceiverThread.c
  targets/FreeRTOS/NXP/_common/WireProtocol_HAL_Interface.c
  targets/FreeRTOS/_common/WireProtocol_ReceiverThread.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/WireProtocol_HAL_Interface.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/WireProtocol_ReceiverThread.c
  targets/TI-SimpleLink/_common/WireProtocol_HAL_Interface.c
  targets/TI-SimpleLink/_common/WireProtocol_ReceiverThread.c
Labels: Type: enhancement

#1885 Fix SOCKETS_MAX_COUNT for FreeRTOS ports
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/lwipopts.h
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/target_common.h.in
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/target_lwipopts.h
  targets/FreeRTOS/_common/include/lwipopts.h
  targets/FreeRTOS/_common/include/targetHAL.h
Labels: Area: Config-and-Build, Type: bug, Type: enhancement

#1886 Allow NXP targets to override all lwIP settings
  targets/FreeRTOS/_common/include/lwipopts.h
Labels: Area: NXP, Type: enhancement

#1883 Add support for System.IO.Directory
  CMake/Modules/FindSystem.IO.FileSystem.cmake
  src/System.IO.FileSystem/nf_sys_io_filesystem.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem.h
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_File.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_FileStream.cpp
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
Labels: Area: Common libs, Type: enhancement

#1892 Add LiLyGo ethernet based ESP32 as a board
  azure-pipelines.yml
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/esp32_os.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Ethernet_Lan8720.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Target_Network.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/esp32_ethernet_options.h.in
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
Labels: Area: Config-and-Build, Type: enhancement

#1895 Adding ESP32 LiLyGo target to the main README
  README.md
  README.zh-cn.md
Labels: Type: documentation

#1896 Work CI-CD
  azure-pipelines-templates/build-chibios-stm32.yml
  azure-pipelines-templates/build-esp32.yml
  azure-pipelines-templates/build-freertos-nxp.yml
  azure-pipelines-templates/build-ti-simplelink.yml
  azure-pipelines-templates/pack-publish-artifacts.yml
  azure-pipelines-templates/publish-cloudsmith.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#1897 Revert "Rework of WireProtocol (#1884)"
  src/CLR/Include/WireProtocol.h
  src/CLR/Include/WireProtocol_HAL_Interface.h
  src/CLR/Include/WireProtocol_Message.h
  src/CLR/WireProtocol/WireProtocol_HAL_Interface.c
  src/CLR/WireProtocol/WireProtocol_Message.c
  targets/ChibiOS/_common/WireProtocol_HAL_Interface.c
  targets/ChibiOS/_common/WireProtocol_ReceiverThread.c
  targets/FreeRTOS/NXP/_common/WireProtocol_HAL_Interface.c
  targets/FreeRTOS/_common/WireProtocol_ReceiverThread.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/WireProtocol_HAL_Interface.c
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/WireProtocol_ReceiverThread.c
  targets/TI-SimpleLink/_common/WireProtocol_HAL_Interface.c
  targets/TI-SimpleLink/_common/WireProtocol_ReceiverThread.c
Labels: Area: Common libs, Type: bug

#1898 Fix System.Device GpioPin.Read
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioPin.cpp
Labels: Area: Common libs, Type: bug
