Repository nanoframework/nf-interpreter, pull requests merged in 2021-11, with the labels that each got.

#2141 Pipelines conditions are now in separated lines
  azure-pipelines-nightly.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#2142 Add System.Device.Pwm to ESP32
  azure-pipelines-nightly.yml
Labels: Area: Config-and-Build

#2143 Fix SPI implementation for ESP32
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/ESP32/_nanoCLR/Windows.Devices.Spi/cpu_spi.cpp
Labels: Type: bug, RTOS: ESP32

#2144 Rework CPU GPIO
  src/PAL/Include/CPU_GPIO_decl.h
  src/System.Device.Gpio/sys_dev_gpio_native_System_Device_Gpio_GpioPin.cpp
  src/Windows.Devices.Gpio/win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp
  targets/ChibiOS/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble _rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS/NXP/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/TI_SimpleLink/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Type: bug, Area: Common libs, RTOS: ESP32

#2145 Fix network interface mapping for ESP-IDF
  targets/ESP32/_Network/NF_ESP32_Wireless.cpp
Labels: Type: bug, RTOS: ESP32

#2146 Work CI-CD
  azure-pipelines-templates/check-code-style.yml
Labels: Area: Config-and-Build

#2147 Update System.Math
  src/CLR/System.Math/nf_native_system_math.cpp
  src/CLR/System.Math/nf_native_system_math.h
Labels: Type: dependencies

#2148 Update System.Math
  src/CLR/System.Math/nf_native_system_math.cpp
  src/CLR/System.Math/nf_native_system_math.h
  src/CLR/System.Math/nf_native_system_math_System_Math.cpp
Labels: Type: bug, Type: enhancement, Type: dependencies

#2149 Fix Math.Max
  src/CLR/System.Math/nf_native_system_math_System_Math.cpp
Labels: Type: bug, Area: Common libs

#2150 Fix double implementation for GCC
  src/CLR/Include/nanoCLR_Runtime__HeapBlock.h
  src/CLR/System.Math/nf_native_system_math_System_Math.cpp
Labels: Type: enhancement, Area: Common libs

#2152 Add check in NativeInit to prevent opening reserved COM port
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ESP32/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Type: bug, RTOS: ESP32

#2153 Fix configuration for ESP32 UART pattern detection
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, RTOS: ESP32

#2154 Rework code handling ReadLine()
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort__.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Area: Targets, Area: Common libs

#2156 ESP32 now uses IDF hardware implementation if available
  CMake/Modules/FindESP32_IDF.cmake
  CMake/Modules/FindNF_CoreCLR.cmake
  src/CLR/Core/nanoSupport_CRC32.c
  targets/ESP32/_Include/esp32_idf.h
  targets/ESP32/_common/CMakeLists.txt
  targets/ESP32/_common/nanoSupport_CRC32.c
Labels: Type: enhancement, RTOS: ESP32

#2157 Rework GetHashCode()
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Include/nanoCLR_Runtime__HeapBlock.h
Labels: Type: bug, Area: Common libs

#2158 Fix bug in unreserving GPIO pins for SD Card
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_nanoFramework_System_IO_FileSystem_SDCard.cpp
Labels: Type: bug, RTOS: ESP32

#2160 Fix FileStream memory leak
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_FileStream.cpp
Labels: Type: bug, RTOS: ESP32

#2161 Adjust lwIP options for ESP32
  targets/ESP32/_IDF/README.md
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble _rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_Include/lwipopts.h
Labels: Area: Config-and-Build, RTOS: ESP32

#2162 Add processing for bad WP packets
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: enhancement

#2155 Update mscorlib
  src/CLR/CorLib/corlib_native.cpp
Labels: do not merge, Area: Common libs, Type: dependencies

#2164 Work CI-CD
  azure-pipelines-nightly.yml
  azure-pipelines.yml
  version.json
Labels: Area: Config-and-Build
