Repository nanoframework/nf-interpreter, pull requests merged in 2021-09, with the labels that each got.

#2024 Fix TLS issue with ESP32 builds
  CMake/Modules/FindNF_Network.cmake
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Memory.cpp
Labels: Area: Config-and-Build, Breaking-change

#2026 Work CI-CD
  CMake/Modules/CHIBIOS_STM32F0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/FindNF_CoreCLR.cmake
  CMake/Modules/FindNF_Debugger.cmake
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindNF_Network.cmake
  CMake/Modules/FindWireProtocol.cmake
  CMake/Modules/FreeRTOS_IMXRT10xx_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC13x2_26x2_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_GCC_options.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
  CMake/binutils.common.cmake
Labels: Area: Config-and-Build

#2027 Work CI-CD
  CMake/binutils.common.cmake
Labels: Area: Config-and-Build

#2028 Fix build of TI SimpleLink targets
  CMake/binutils.TI_SimpleLink.cmake
  targets/TI_SimpleLink/TI_CC1352R1_LAUNCHXL/CMakeLists.txt
  targets/TI_SimpleLink/TI_CC3220SF_LAUNCHXL/CMakeLists.txt
  targets/TI_SimpleLink/_common/CMakeLists.txt
Labels: Area: Config-and-Build

#2030 Fix Serial receive in TI SimpleLink
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialDevice.cpp
Labels: Type: bug, Area: TI-SimpleLink

#2022 PSRAM pins in ESP32 are now reserved only if needed
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
Labels: Type: enhancement, Area: ESP32

#2031 Update STM32_IRQ_USART1_PRIORITY to 3
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
Labels: Type: enhancement, Area: Azure-RTOS

#2032 Fix mapping of ADC3 IN8
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/managed_helpers/STM32F769I_DISCOVERY.Adc.cs
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_windows_devices_adc_config.cpp
Labels: Type: bug, Area: STM32

#2033 Fix TRACE calls
  src/CLR/Debugger/Debugger.cpp
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: bug, Area: Common libs

#2034 Fixing stubs inclusion for several components
  CMake/Modules/FindNF_CoreCLR.cmake
Labels: Area: Config-and-Build

#2036 Fix RTOS names in cmake-variants to correct case
  .vscode/cmake-variants-DEVCONTAINER.json
  .vscode/cmake-variants.TEMPLATE.json
  targets/ChibiOS/NETDUINO3_WIFI/cmake-variants.json
  targets/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/ChibiOS/ST_NUCLEO64_F091RC/cmake-variants.json
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/cmake-variants.json
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/README.md
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/cmake-variants.json
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/cmake-variants.json
  targets/TI_SimpleLink/TI_CC1352R1_LAUNCHXL/cmake-variants.json
  targets/TI_SimpleLink/TI_CC3220SF_LAUNCHXL/cmake-variants.json
Labels: Type: bug, Area: Config-and-Build

#2037 Add missing COMPort parameter to install-nf-tools.ps1
  install-scripts/install-nf-tools.ps1
Labels: Area: Config-and-Build

#2038 Cleanup rework trace
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindWireProtocol.cmake
  CMakeLists.txt
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  src/CLR/Include/WireProtocol_Message.h
  src/CLR/Messaging/Messaging.cpp
  src/CLR/WireProtocol/WireProtocol_Message.c
  targets/ChibiOS/_common/WireProtocol_HAL_Interface.c
  targets/TI_SimpleLink/_common/WireProtocol_HAL_Interface.c
Labels: Type: enhancement, Area: Config-and-Build, Area: Common libs

#2039 Improvements in TRACE for Wire Protocol
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindWireProtocol.cmake
  CMakeLists.txt
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol_Message.h
  src/CLR/Messaging/Messaging.cpp
  src/CLR/WireProtocol/WireProtocol_Message.c
  targets/ChibiOS/_common/WireProtocol_HAL_Interface.c
  targets/TI_SimpleLink/_common/WireProtocol_HAL_Interface.c
Labels: Type: enhancement

#2040 Update TRACE for WP to match develop branch
  CMake/Modules/FindNF_CoreCLR.cmake
  src/CLR/Helpers/nanoprintf/nanoprintf.c
  src/CLR/WireProtocol/WireProtocol_Message.c
  targets/AzureRTOS/Maxim/_common/WireProtocol_HAL_Interface.c
  targets/AzureRTOS/ST/_common/WireProtocol_HAL_Interface.c
Labels: Type: enhancement

#2043 Fix ADC2 and tidy up
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
Labels: Type: bug, Status: DONE, Area: ESP32

#2045 Add macro to clean-up build artifacts
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.ESP32.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
  CMake/binutils.common.cmake
Labels: Area: Config-and-Build

#2046 Made trace variable visible
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: bug, Area: Common libs

#2044 Add NF_TRACE_TO_STDIO CMake option
  .vscode/cmake-variants-DEVCONTAINER.json
  .vscode/cmake-variants.TEMPLATE.json
  CMake/AzureRTOS_target_os.h.in
  CMake/ChibiOS_target_os.h.in
  CMake/ESP32_target_os.h.in
  CMake/FreeRTOS_target_os.h.in
  CMake/Modules/FindNF_CoreCLR.cmake
  CMake/TI_SimpleLink_target_os.h.in
  CMake/binutils.common.cmake
  CMakeLists.txt
  src/CLR/Debugger/Debugger.cpp
  src/PAL/COM/GenericPort_stdio.c
  src/PAL/Include/nanoPAL_COM.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/CMakeLists.txt
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/board.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/cmake-variants.json
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/common/serialcfg.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/main.c
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_stdio_config.c
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_stdio_config.h
  targets/AzureRTOS/ST/_common/CMakeLists.txt
  targets/AzureRTOS/ST/_common/Target_GenericPort_stdio.c
  targets/AzureRTOS/ST/_include/Target_GenericPort_stdio.h
  targets/AzureRTOS/_common/nanoCLR/nanoCRT.cpp
Labels: Type: enhancement

#2047 Add support for System.IO.Ports to AzureRTOS on ST_B_L475E_IOT01A
  azure-pipelines.yml
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/cmake-variants.json
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/common/Device_BlockStorage-DEBUG.c
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/common/Device_BlockStorage.c
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/STM32L475xG_booter-DEBUG.ld
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/STM32L475xG_booter.ld
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/STM32L475xG_CLR-DEBUG.ld
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/STM32L475xG_CLR.ld
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_windows_devices_serialcommunication_config.cpp
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_windows_devices_serialcommunication_config.h
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
Labels: Type: enhancement, Area: Azure-RTOS

#2051 Fix defines for TRACE_LIMIT #defines
  src/CLR/Include/WireProtocol_Message.h
Labels: Type: bug

#2048 Add SPI support to AzureRTOS on ST_B_L475EIOT01A
  targets/AzureRTOS/Maxim/_nanoCLR/target_platform.h.in
  targets/AzureRTOS/MicroBit/_nanoCLR/target_platform.h.in
  targets/AzureRTOS/Nordic/_nanoCLR/target_platform.h.in
  targets/AzureRTOS/RaspberryPi/_nanoCLR/target_platform.h.in
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/halconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_system_device_spi_config.cpp
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_windows_devices_spi_config.cpp
  targets/AzureRTOS/ST/_nanoCLR/CMakeLists.txt
  targets/AzureRTOS/ST/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.Spi/sys_dev_spi_native_target.h
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.Spi/cpu_spi.cpp
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.Spi/win_dev_spi_native_target.h
  targets/AzureRTOS/ST/_nanoCLR/targetHAL.cpp
  targets/AzureRTOS/ST/_nanoCLR/target_platform.h.in
  targets/AzureRTOS/_common/include/TargetHAL_Spi.h
Labels: Type: enhancement

#2049 Add I2C to Azure RTOS
  azure-pipelines.yml
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/cmake-variants.json
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_system_device_i2c_config.cpp
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/target_windows_devices_i2c_config.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_target.h
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2C_I2cDevice.cpp
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_Windows_Devices_I2c_I2cController.cpp
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.I2c/win_dev_i2c_native_target.h
Labels: Type: enhancement, Area: Azure-RTOS

#2060 Fix PWM deviceSelectorString
  targets/ChibiOS/_nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native_Windows_Devices_Pwm_PwmController.cpp
Labels: Type: bug, Area: STM32

#2052 Adding System.Device.Pwm
  .devcontainer/devcontainer.json
  .vscode/cmake-variants-DEVCONTAINER.json
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindSystem.Device.Pwm.cmake
  azure-pipelines.yml
  src/System.Device.Pwm/sys_dev_pwm_native.cpp
  src/System.Device.Pwm/sys_dev_pwm_native.h
  targets/ChibiOS/NETDUINO3_WIFI/cmake-variants.json
  targets/ChibiOS/ORGPAL_PALTHREE/cmake-variants.json
  targets/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/ChibiOS/ST_NUCLEO64_F091RC/cmake-variants.json
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/cmake-variants.json
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/cmake-variants.json
  targets/ChibiOS/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native_Windows_Devices_Pwm_PwmPin.cpp
  targets/TI_SimpleLink/TI_CC3220SF_LAUNCHXL/cmake-variants.json
  targets/TI_SimpleLink/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp
Labels: Type: enhancement, Area: Config-and-Build

#2067 Fix inclusion of STM32 Cube package in assemblies
  CMake/binutils.ChibiOS.cmake
Labels: Area: Config-and-Build

#2069 Fix declaration of Windows.Storage assembly
  src/Windows.Storage/win_storage_native.h
Labels: Type: dependencies

#2071 Work in SPIFFS
  src/HAL/Include/nanoHAL_Windows_Storage.h
  targets/ChibiOS/ORGPAL_PALTHREE/spiffs_config.h
  targets/ChibiOS/ORGPAL_PALTHREE/target_spiffs.c
  targets/ChibiOS/ORGPAL_PALTHREE/target_spiffs.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/spiffs_config.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_spiffs.c
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_spiffs.h
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_FileIO.cpp
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_target.h
  targets/ChibiOS/_spiffs/hal_spiffs.c
  targets/ChibiOS/_spiffs/hal_spiffs.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
Labels: Type: bug, Type: enhancement, Area: STM32, Area: Common libs

#2072 Fix call to set native pin configuration
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native_Hardware_Esp32_Configuration.cpp
Labels: Type: bug, Area: ESP32

#2073 Adding support for I2S pin configuration on ESP32
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Include/Esp32_DeviceMapping.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/Esp32_DeviceMapping.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
Labels: Type: enhancement

#2075 Fix order of rules inclusion in ORGPAL3
  targets/ChibiOS/ORGPAL_PALTHREE/nanoCLR/STM32F76xx_CLR-DEBUG.ld
  targets/ChibiOS/ORGPAL_PALTHREE/nanoCLR/STM32F76xx_CLR.ld
Labels: Area: Config-and-Build, Area: STM32

#2078 Work on WP and messaging
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/WireProtocol_Message.h
  src/CLR/Include/nanoCLR_Messaging.h
  src/CLR/Messaging/Messaging.cpp
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: bug, Type: enhancement, Area: Common libs

#2077 Fix CLR_DBG_Debugger::Monitor_FlashSectorMap
  src/CLR/Debugger/Debugger.cpp
Labels: Type: bug, Area: Common libs

#2076 Improvements in malloc/free
  src/CLR/CorLib/corlib_native_System_BitConverter.cpp
  src/HAL/Include/nanoHAL_v2.h
  targets/ChibiOS/_common/platform_heap.c
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS/NXP/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/platform_heap.c
  targets/TI_SimpleLink/_common/platform_heap.c
  targets/TI_SimpleLink/_nanoCLR/targetSimpleLinkCC32xx_LinkLocalTask.c
  targets/win32/nanoCLR/platform_heap.cpp
Labels: Area: Config-and-Build

#2054 Fix spelling of "successful" in comments
  src/CLR/Include/WireProtocol_HAL_Interface.h
  src/PAL/COM/ComDirector.cpp
  src/PAL/Include/nanoPAL_BlockStorage.h
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_FileStream.cpp
  targets/ChibiOS/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/ChibiOS/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS/NXP/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/TI_SimpleLink/_common/targetHAL_ConfigurationManager_CC13x2_26x2.cpp
  targets/TI_SimpleLink/_common/targetHAL_ConfigurationManager_CC32xx.cpp
  targets/TI_SimpleLink/_nanoCLR/Windows.Devices.Gpio/cpu_gpio.cpp
  targets/win32/Include/TargetPAL_BlockStorage.h
Labels: Type: documentation

#2079 Work on WP command handlers
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Messaging/Messaging.cpp
Labels: Type: enhancement, Area: Common libs

#2080 Improve S.IO.Ports
  CMake/Modules/FindSystem.IO.Ports.cmake
  src/System.IO.Ports/sys_io_ser_native.cpp
  src/System.IO.Ports/sys_io_ser_native.h
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort__.cpp
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort_stubs.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialDevice.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: enhancement, Area: Config-and-Build, Area: Targets, Type: dependencies

#2081 Fix potential memory leaks in S.IO.Ports code
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialDevice.cpp
Labels: Type: bug, Type: enhancement

#2082 Rework Messaging
  src/CLR/Messaging/Messaging.cpp
Labels: Type: enhancement

#2083 Simpler top-level cmakelists
  CMakeLists.txt
Labels: Area: Config-and-Build
