Repository nanoframework/nf-interpreter, pull requests merged in 2021-10, with the labels that each got.

#2086 Fix serial implementation for TI
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: bug

#2085 Use extern "C" to remove C++ name mangling
  src/CLR/WireProtocol/targetHAL_time.cpp
  src/HAL/Include/nanoHAL_Time.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_spiffs.c
  targets/ChibiOS/_common/targetHAL_Time.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/common/targetHAL_Time.cpp
  targets/TI_SimpleLink/_common/platformHAL_Time.cpp
Labels: Type: enhancement

#2087 Add missing macros for Azure CMake
  CMake/binutils.AzureRTOS.cmake
Labels: Area: Config-and-Build, hacktoberfest-accepted

#2089 Bring changes in W.D.SerialComm from develop
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Type: enhancement, hacktoberfest-accepted

#2088 Move add_subdirectory(targets/AzureRTOS)
  CMakeLists.txt
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/AzureRTOS/ST/_nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_target.h
Labels: Area: Config-and-Build, hacktoberfest-accepted

#2090 set default AzureRTOS version to v6.1.8_rel
  targets/AzureRTOS/CMakeLists.txt
Labels: Area: Config-and-Build, hacktoberfest-accepted

#2092 Add API to get certificate store and device certificate
  src/HAL/Include/nanoHAL_ConfigurationManager.h
  src/HAL/nanoHAL_ConfigurationManager.c
  src/HAL/nanoHAL_ConfigurationManager_stubs.c
Labels: Type: enhancement

#2093 Rework TLS to use new config manager API
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_generic_init_internal.cpp
Labels: Type: enhancement, Area: Common libs

#2140 Add Get Native Memory Info on ESP32
  CMake/Modules/FindnanoFramework.Hardware.Esp32.cmake
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native_Hardware_Esp32_NativeMemory.cpp
Labels: Type: enhancement
