Repository nanoframework/nf-interpreter, pull requests merged in 2021-01, with the labels that each got.

#1824 StorageFile DateTime Heap corruption fix
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFile.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_StorageFolder.cpp
Labels: Area: Interpreter, Type: bug, do not merge

#1825 Update mscorlib declaration
  src/CLR/CorLib/corlib_native.cpp
Labels: Area: Common libs, Type: dependencies

#1826 Changes for RS485 mode
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.cpp
  src/Windows.Devices.SerialCommunication/win_dev_serial_native.h
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS/NXP/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Area: ESP32, Type: enhancement

#1829 Multi Cast Delegate with Struct types cause CLR_E_WRONG_TYPE exception
  src/CLR/Core/CLR_RT_StackFrame.cpp
Labels: Area: Interpreter, Status: DONE, Type: bug

#1827 Add SPI2 to STM32F769I
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
  targets/CMSIS-OS/ChibiOS/ST_STM32F769I_DISCOVERY/target_windows_devices_spi_config.cpp
Labels: Type: enhancement

#1830 Adding Dev Container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/scripts/non-toot-user.sh
  .vscode/cmake-variants-DEVCONTAINER.json
  CMake/binutils.TI_SimpleLink.cmake
  CMake/toolchain.xtensa-esp32-elf.cmake
  src/PAL/Lwip/lwIP_Sockets.cpp
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/IDF/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Lwip/CMakeLists.txt
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Ethernet_Lan8720.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
  targets/TI-SimpleLink/TI_CC3220SF_LAUNCHXL/CMakeLists.txt
Labels: Area: Config-and-Build, Type: dependencies, Type: enhancement
