Repository nanoframework/nf-interpreter, pull requests merged in 2021-06, with the labels that each got.

#1942 Restore FindTypeDef code for reflection types
  src/CLR/Core/TypeSystem.cpp
Labels: Area: Interpreter, Type: enhancement

#1943 Enable SmartConfig
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
Labels: Type: bug

#1944 Fix FromBase64
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Convert.cpp
Labels: Type: bug, Type: dependencies

#1945 Add base64 conversions to Win32 CLR
  targets/win32/nanoCLR/Various.cpp
  targets/win32/nanoCLR/base64.cpp
  targets/win32/nanoCLR/nanoCLR.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj.filters
Labels: Type: enhancement

#1946 Rework default base64 implementation
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/CLR/Helpers/Base64/base64.c
  src/CLR/Helpers/Base64/base64.h
  targets/win32/nanoCLR/base64.cpp
Labels: Area: Common libs, Type: bug

#1947 Enable support for all base conversions to WIN32 CLR
  src/CLR/CorLib/CorLib.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Config-and-Build

#1948 Fixes in System.IO.Port
  azure-pipelines-templates/nb-gitversioning.yml
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Area: ESP32, Area: NXP, Area: STM32, Type: bug, Type: enhancement

#1949 nanoCLR_Debugging: Add c_Monitor_TargetInfo to CLR_DBG_Commands
  src/CLR/Include/nanoCLR_Debugging.h
Labels: Area: Common libs, Type: bug

#1950 targets: win32: targetPAL_Events: Fix memory leak
  targets/win32/nanoCLR/targetPAL_Events.cpp
Labels: Area: WIN32, Type: bug

#1951 Fixes to String.Format caught by unit tests and comparing to .Net Core 5
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Number.cpp
  src/CLR/Helpers/nanoprintf/nanoprintf.c
Labels: Type: enhancement

#1952 Fix WiFi Connect
  src/CLR/Core/Hardware/Hardware.cpp
  src/CLR/Include/nanoCLR_Hardware.h
  src/CLR/Include/nanoCLR_Runtime.h
  src/HAL/Include/nanoHAL_v2.h
  src/PAL/Include/nanoPAL_Sockets.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_SmartConfig.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Target_Network.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/targetHAL_Network.cpp
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Wifi/win_dev_wifi_native_Windows_Devices_WIFI_WifiAdapter.cpp
Labels: Area: ESP32, Status: DONE, Type: bug

#1953 Update System.Net declaration
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
Labels: Type: dependencies

#1954 Update mscorlib declaration
  src/CLR/CorLib/corlib_native.cpp
Labels: Type: dependencies

#1955 Work CI-CD
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/Core/Core.vcxproj
  src/CLR/Core/Hardware/Hardware.vcxproj
  src/CLR/Core/Hardware/Hardware_stub.vcxproj
  src/CLR/Core/InterruptHandler/InterruptHandler.vcxproj
  src/CLR/Core/InterruptHandler/InterruptHandler_stub.vcxproj
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.vcxproj
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher_stub.vcxproj
  src/CLR/Core/RPC/RPC.vcxproj
  src/CLR/Core/RPC/RPC_stub.vcxproj
  src/CLR/Core/Serialization/Serialization.vcxproj
  src/CLR/Core/Serialization/Serialization_stub.vcxproj
  src/CLR/Debugger/Debugger.vcxproj
  src/CLR/Debugger/Debugger_stub.vcxproj
  src/CLR/Diagnostics/Diagnostics.vcxproj
  src/CLR/Diagnostics/Diagnostics_stub.vcxproj
  src/CLR/Messaging/Messaging.vcxproj
  src/CLR/Messaging/Messaging_stub.vcxproj
  src/CLR/Startup/Startup.vcxproj
  src/CLR/System.Math/System.Math.vcxproj
  src/CLR/WireProtocol/WireProtocol.vcxproj
  src/DeviceInterfaces/Networking.Sntp/Networking.Sntp.vcxproj
  src/DeviceInterfaces/System.Net/System.Net.vcxproj
  src/System.IO.Ports/System.IO.Ports.vcxproj
  src/Windows.Storage/Windows.Storage.vcxproj
  src/nanoFramework.ResourceManager/nanoFramework.ResourceManager.vcxproj
  src/nanoFramework.Runtime.Native/Runtime.Native.vcxproj
  src/nanoFramework.System.Collections/System.Collections.vcxproj
  src/nanoFramework.System.Text/System.Text.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Config-and-Build

#1956 Fix unbox.any for GUID type
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Type: bug

#1957 Work CI-CD
  azure-pipelines-templates/download-install-llvm.yml
Labels: Area: Config-and-Build

#1959 Fix esp32 build options
  azure-pipelines-templates/build-esp32.yml
Labels: Area: Config-and-Build

#1961 Fix System.IO.Port declaration
  src/System.IO.Ports/sys_io_ser_native.cpp
  src/System.IO.Ports/sys_io_ser_native.h
Labels: Area: Common libs, Type: bug

#1962 Update System.IO.Port declaration
  src/System.IO.Ports/sys_io_ser_native.cpp
  src/System.IO.Ports/sys_io_ser_native.h
  targets/win32/nanoCLR/Generated/CLR_RT_InteropAssembliesTable.cpp
Labels: Type: dependencies

#1963 Add NOP definition to TI Simplelink
  targets/TI-SimpleLink/_Include/targetHAL.h
Labels: Area: TI-SimpleLink, Type: enhancement

#1964 Add Sys.IO.Port to TI SimpleLink
  CMake/Modules/FindSystem.IO.Ports.cmake
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_system_io_serial_config.cpp
  targets/TI-SimpleLink/TI_CC1352R1_LAUNCHXL/target_system_io_serial_config.h
  targets/TI-SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialDevice.cpp
  targets/TI-SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: enhancement

#1965 Increase priority of network threads for STM32 targets
  targets/ChibiOS/_Include/lwipopts.h
  targets/ChibiOS/_Lwip/nf_lwipthread.h
Labels: Area: ChibiOS, Type: enhancement

#1967 Update EasyLink code for SDK
  targets/TI-SimpleLink/_common/easylink/EasyLink.c
  targets/TI-SimpleLink/_common/easylink/EasyLink.h
Labels: Area: TI-SimpleLink, Type: enhancement

#1968 Remove GenericPort_Write for SimpleLink
  targets/TI-SimpleLink/_common/GenericPort.cpp
Labels: Area: TI-SimpleLink, Breaking-change

#1969 Fix debugger discovery
  src/CLR/Debugger/Debugger.cpp
  targets/win32/Include/targetHAL.h
Labels: Area: Common libs, Type: bug
