Repository nanoframework/nf-interpreter, pull requests merged in 2021-02, with the labels that each got.

#1831 Adjusting Dev Container for hex2dfu
  .devcontainer/Dockerfile
  .vscode/cmake-variants-DEVCONTAINER.json
  targets/CMSIS-OS/ChibiOS/CMakeLists.txt
Labels: Type: bug, Type: enhancement

#1833 Fix InfiniteTimeSpan
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
Labels: Type: bug

#1648 Adds SQLite souce
  CMake/Modules/FindSQLite.cmake
  CMake/SQLite.CMakeLists.cmake.in
  CMakeLists.txt
  azure-pipelines.yml
  src/System.Data.Sqlite/System_Data_Sqlite.cpp
  src/System.Data.Sqlite/System_Data_Sqlite.h
  src/System.Data.Sqlite/System_Data_Sqlite_System_Data_Sqlite_SqliteCommand.cpp
Labels: Type: enhancement, do not merge

#1834 Adding pull script for all cloned tags and branches in Dev Container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/scripts/git-pull-repos.sh
Labels: Area: Config-and-Build

#1836 Add entry in PWM library to include support STM32F765xx CPUs
  targets/CMSIS-OS/ChibiOS/nanoCLR/Windows.Devices.Pwm/win_dev_pwm_native_Windows_Devices_Pwm_PwmPin.cpp
Labels: Area: STM32, Type: enhancement

#1835 Update flash driver to include support STM32F765xx CPUs
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.c
  targets/CMSIS-OS/ChibiOS/nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.h
Labels: Area: ChibiOS, Type: enhancement

#1841 TinyPrintf replaced with nanoprintf, #693
  CMake/Modules/FindNF_CoreCLR.cmake
  src/CLR/CorLib/CorLib.h
  src/CLR/CorLib/corlib_native_System_Globalization_DateTimeFormat.cpp
  src/CLR/CorLib/corlib_native_System_Number.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_Assembly.cpp
  src/CLR/Diagnostics/Diagnostics.h
  src/CLR/Helpers/TinyPrintf/printf.c
  src/CLR/Helpers/TinyPrintf/printf.h
  src/CLR/Helpers/nanoprintf/nanoprintf.c
  src/CLR/Helpers/nanoprintf/nanoprintf.h
  targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.SerialCommunication/win_dev_serial_native_Windows_Devices_SerialCommunication_SerialDevice.cpp
Labels: Type: dependencies, Type: enhancement
