Repository nanoframework/nf-interpreter, pull requests merged in 2022-01, with the labels that each got.

#2205 Fix loading the client certificate from the store
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_generic_init_internal.cpp
  targets/ESP32/_common/targetHAL_ConfigurationManager.cpp
Labels: Type: bug

#2209 Align lwIP configs
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Area: Config-and-Build

#2206 Improve README
  README.md
Labels: Type: documentation

#2207 Remove netduino3 from reference target build files
  .vscode/cmake-variants-DEVCONTAINER.json
  build.ps1
Labels: Area: Config-and-Build

#2208 Fix ST_NUCLEO64_F091RC build options
  build.ps1
Labels: Area: Config-and-Build

#2202 Update ESP32 build settings to match CI
  .vscode/cmake-variants-DEVCONTAINER.json
Labels: Area: Config-and-Build

#2210 Fix SDK options for ESP32_BLE_REV3
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Area: Config-and-Build

#2204 Update System.Net declaration
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.h
Labels: Type: dependencies

#2212 Update System.Net declaration
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
Labels: Type: dependencies

#2211 Increase reserved memory for ESP32 malloc
  targets/ESP32/_nanoCLR/Memory.cpp
Labels: Type: bug, Area: Config-and-Build

#2213 Update (and rename) System.Device.WiFi
  .vscode/cmake-variants-DEVCONTAINER.json
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindSystem.Device.WiFi.cmake
  CMake/Modules/FindWindows.Devices.Wifi.cmake
  CMakeLists.txt
  CMakeSettings.SAMPLE.json
  CMakeSettings.json
  azure-pipelines-nightly.yml
  azure-pipelines.yml
  build.ps1
  src/PAL/Include/nanoPAL_Sockets.h
  src/System.Device.Wifi/sys_dev_wifi_native.cpp
  src/System.Device.Wifi/sys_dev_wifi_native.h
  src/Windows.Devices.Wifi/win_dev_wifi_native.cpp
  src/Windows.Devices.Wifi/win_dev_wifi_native.h
  targets/ESP32/ESP32/cmake-variants.json
  targets/ESP32/ESP32_S2/cmake-variants.json
  targets/ESP32/_nanoCLR/System.Device.Wifi/sys_dev_wifi_native_System_Device_WiFi_WiFiAdapter.cpp
  targets/ESP32/_nanoCLR/Windows.Devices.Wifi/win_dev_wifi_native.h
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/README.md
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/cmake-variants.json
Labels: Area: Config-and-Build, Type: dependencies

#2214 Fix check for STM32_CUBE_PACKAGE_SOURCE
  CMake/Modules/STM32_CubePackage.cmake
Labels: Area: Config-and-Build

#2217 Fix SDK Option for ESP32_BLE_REV3
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Area: Config-and-Build

#2219 Improve build powershell script
  build.ps1
Labels: Area: Config-and-Build

#2220 Fix memory leak with Directory.GetFiles() and GetDirectories()
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
Labels: Type: bug

#2221 Fixes in get/set socket options
  src/PAL/Lwip/lwIP_Sockets.cpp
Labels: Type: bug, Area: Common libs

#2215 Improvements in CMAKE
  .gitignore
  CMake/Modules/STM32_CubePackage.cmake
  CMake/binutils.common.cmake
  CMakeLists.txt
  targets/ChibiOS/CMakeLists.txt
  targets/ESP32/CMakeLists.txt
  targets/FreeRTOS/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/TI_SimpleLink/CMakeLists.txt
Labels: Area: Config-and-Build

#2224 Work CD-CI
  azure-pipelines-templates/pack-publish-managed-helpers.yml
  azure-pipelines-templates/pack-publish-ti-sl-managed-helpers.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#2223 Fix return type of HeapBlock GetHashCode()
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Include/nanoCLR_Runtime__HeapBlock.h
Labels: Type: bug

#2222 ESP32 SD card updates, remove deprecated calls and optimize
  CMake/Modules/FindSystem.IO.FileSystem.cmake
  CMake/Modules/FindWindows.Storage.cmake
  targets/ESP32/_Include/Target_Windows_Storage.h
  targets/ESP32/_common/Target_Windows_Storage.c
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_nanoFramework_System_IO_FileSystem_SDCard.cpp
  targets/ESP32/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_Devices_SDCard.cpp
  targets/ESP32/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_FileIO.cpp
Labels: Platform: ESP32

#2235 Fix object not initialized
  src/CLR/Core/CLR_RT_HeapBlock.cpp
Labels: Type: bug

#2232 Fixing ReadLine() for multi characters
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort__.cpp
Labels: Type: bug

#2229 Enable W.Storage in ESP_PICO
  azure-pipelines-nightly.yml
Labels: Area: Config-and-Build

#2231 Align multiple boards in build.ps1 with CI
  build.ps1
Labels: Area: Config-and-Build

#2236 Add native support for DateTime.Parse
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/HAL/Include/nanoHAL_Time.h
  src/HAL/nanoHAL_Time.cpp
  targets/ChibiOS/ST_NUCLEO64_F091RC/common/Device_BlockStorage.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/STM32F091xC_CLR.ld
Labels: Type: enhancement, Area: Common libs, Type: dependencies

#2237 Fix missing var assignment
  src/CLR/CorLib/corlib_native_System_Convert.cpp
Labels: Type: enhancement, Area: Common libs

#2239 Device host name is not composed with last 3 bytes of MAC address
  targets/ChibiOS/_common/targetHAL_Network.cpp
  targets/ESP32/_common/targetHAL_Network.cpp
  targets/FreeRTOS/NXP/_nanoCLR/targetHAL_Network.cpp
Labels: Type: enhancement, Breaking-change

#2240 Add S.R.Environment
  CMake/Modules/FindNF_CoreCLR.cmake
  src/nanoFramework.Runtime.Native/Runtime.Native.vcxproj
  src/nanoFramework.Runtime.Native/Runtime.Native.vcxproj.filters
  src/nanoFramework.Runtime.Native/nf_rt_native.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native.h
  src/nanoFramework.Runtime.Native/nf_rt_native_System_Environment.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Hardware_SystemInfo.cpp
Labels: Type: enhancement, Area: Common libs, Type: dependencies

#2241 Improvements in Reflection
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Reflection_MethodBase.cpp
  src/CLR/CorLib/corlib_native_System_Type.cpp
Labels: Type: enhancement, Type: dependencies

#2242 Fix search flags for class constructors in GetConstructors()
  src/CLR/CorLib/corlib_native_System_Type.cpp
Labels: Type: bug

#2243 Update mbedTLS to 2.28
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/Dockerfile.ESP32
  .devcontainer/Dockerfile.TI
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  .devcontainer/sources/Dockerfile.TI
  .github/workflows/all.yaml
  .github/workflows/azurertos.yaml
  .github/workflows/chibios.yaml
  .github/workflows/esp32.yml
  .github/workflows/ti.yaml
  CMake/Modules/FindmbedTLS.cmake
  src/CLR/Helpers/Base64/base64.c
  targets/ChibiOS/CMakeLists.txt
  targets/ESP32/CMakeLists.txt
Labels: Area: Config-and-Build, Type: dependencies
