Repository nanoframework/nf-interpreter, pull requests merged in 2022-12, with the labels that each got.

#2481 Debug and Console Write are now working on virtual device
  targets/netcore/nanoFramework.nanoCLR/CLRStartup.cpp
  targets/win32/nanoCLR/CLRStartup.cpp
Labels: Type: bug, Platform: Virtual Device & WIN32

#2485 Fix virtual device app exit
  src/CLR/Debugger/Debugger.cpp
  targets/win32/nanoCLR/targetPAL_Events.cpp
Labels: Type: bug, Platform: Virtual Device & WIN32

#2486 Fix assembly info version for WIN build
  azure-pipelines.yml
  src/CLR/Debugger/Debugger.vcxproj
  targets/netcore/nanoFramework.nanoCLR/nanoFramework.nanoCLR.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Config-and-Build

#2487 Improve CLR exit
  targets/netcore/nanoFramework.nanoCLR/CLRStartup.cpp
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#2489 Fix wrong exception with Wi-Fi Scan
  targets/ESP32/_nanoCLR/System.Device.Wifi/sys_dev_wifi_native_System_Device_Wifi_WifiAdapter.cpp
Labels: Type: bug, Platform: ESP32

#2490 Fix compiler warning about uninit var
  src/System.Device.Spi/sys_dev_spi_native_System_Device_Spi_SpiDevice.cpp
Labels: Type: enhancement, Area: Common libs

#2491 Rename struct element for clarity
  src/PAL/Include/CPU_SPI_decl.h
  src/System.Device.Spi/sys_dev_spi_native_System_Device_Spi_SpiDevice.cpp
Labels: Type: enhancement, Area: Common libs

#2492 Add System.Runtime.Serialization
  CMake/Modules/FindNF_CoreCLR.cmake
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindSystem.Runtime.Serialization.cmake
  CMakeLists.txt
  CMakeUserPresets.TEMPLATE.json
  nf.props
  src/CLR/CorLib/corlib_native_System_WeakReference.cpp
  src/CLR/Core/Serialization/BinaryFormatter.cpp
  src/CLR/Core/Serialization/BinaryFormatter_stub.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Include/nanoCLR_Runtime__Serialization.h
  src/System.Runtime.Serialization/System.Runtime.Serialization.vcxproj
  src/System.Runtime.Serialization/System.Runtime.Serialization.vcxproj.filters
  src/System.Runtime.Serialization/nf_system_runtime_serialization.cpp
  src/System.Runtime.Serialization/nf_system_runtime_serialization.h
  src/System.Runtime.Serialization/nf_system_runtime_serialization_System_Runtime_Serialization_Formatters_Binary_BinaryFormatter.cpp
  targets/netcore/nanoCLR.sln
  targets/netcore/nanoFramework.nanoCLR/nanoFramework.nanoCLR.vcxproj
  targets/win32/nanoCLR.sln
  targets/win32/nanoCLR/Generated/CLR_RT_InteropAssembliesTable.cpp
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Type: enhancement, Area: Config-and-Build, Area: Common libs

#2493 Fix parsing parameters
  targets/win32/nanoCLR/main.cpp
Labels: Type: bug, Platform: Virtual Device & WIN32

#2494 Move global preprocessor definitions to nf.props
  nf.props
  src/CLR/Core/Core.vcxproj
  src/CLR/Debugger/Debugger.vcxproj
  src/CLR/WireProtocol/WireProtocol.vcxproj
  targets/netcore/nanoFramework.nanoCLR/nanoFramework.nanoCLR.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Config-and-Build, Platform: Virtual Device & WIN32

#2495 Fix lookup assembly
  src/CLR/Core/CLR_RT_SystemAssembliesTable.cpp
Labels: Type: bug, Area: Common libs

#2496 Improvements in virtual device
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandLineOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/README.md
  targets/netcore/nanoFramework.nanoCLR.Host/Port/NativeWireProtocolPort.cs
  targets/netcore/nanoFramework.nanoCLR.Host/Port/Serial/SerialPort.cs
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#2497 Work CI-CD
  azure-pipelines-nightly.yml
  azure-pipelines-templates/download-install-llvm.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#2498 Improve nf_generate_bin_package to declare BYPRODUCTS
  CMake/binutils.common.cmake
Labels: Area: Config-and-Build

#2499 Fix comparison for IDF path
  targets/ESP32/CMakeLists.txt
Labels: Area: Config-and-Build

#2502 Port changes from ChibiOS v21.11.3
  targets/ChibiOS/_Lwip/nf_lwipthread.c
Labels: Type: bug, Type: enhancement, Platform: STM32

#2500 Fix output of build messages
  CMake/Modules/FindChibiOS.cmake
  CMake/Modules/FindFreeRTOS.cmake
  CMake/Modules/FindNF_HALCore.cmake
  CMake/Modules/FindRPIPicoSdk.cmake
  CMake/Modules/FindSystem.Device.Pwm.cmake
  CMake/Modules/FindSystem.Device.Spi.cmake
  CMake/Modules/FindSystem.IO.Ports.cmake
  CMake/Modules/FindWireProtocol.cmake
  CMake/Modules/FindnanoFramework.Device.Bluetooth.cmake
Labels: Area: Config-and-Build

#2501 ESP32 build now outputs IDF size summary
  CMake/binutils.ESP32.cmake
  targets/ESP32/_IDF/project_elf_src_esp32.c
  targets/ESP32/_IDF/project_elf_src_esp32c3.c
  targets/ESP32/_IDF/project_elf_src_esp32s2.c
Labels: Area: Config-and-Build

#2503 Fix check for missing ffconf header in IDF
  targets/ESP32/CMakeLists.txt
Labels: Area: Config-and-Build

#2343 Update mscorlib declaration
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
Labels: Type: dependencies
