Repository nanoframework/nf-interpreter, pull requests merged in 2022-06, with the labels that each got.

#2355 Fix some minor spelling mistakes
  .vscode/cmake-variants.TEMPLATE.json
  CMake/binutils.common.cmake
  CMakeLists.txt
  src/HAL/Include/nanoHAL_ConfigurationManager.h
  targets/FreeRTOS/NXP/_common/device/MIMXRT1062.h
  targets/FreeRTOS/NXP/_common/xip/evkmimxrt1060_flexspi_nor_config.h
Labels: Area: Config-and-Build

#2341 Optimized opaque Bitmap rectangle fill. BitBlt now accepts both full bitmap and screen coordinates
  src/nanoFramework.Graphics/Graphics/Core/Graphics.h
  src/nanoFramework.Graphics/Graphics/Core/GraphicsDriver.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Display.h
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ILI9342_320x240_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Otm8009a_DSI_Video_Mode.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1306_128x64.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1331_94x64_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7735S_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Bitmap.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
Labels: Type: enhancement, Breaking-change

#2360 Fix usage of global compiler definitions
  CMake/binutils.common.cmake
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/CMakeLists.txt
  targets/ChibiOS/ORGPAL_PALTHREE/CMakeLists.txt
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/CMakeLists.txt
Labels: Area: Config-and-Build

#2362 Fix descriptor events and add service UUID to advert
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/esp32_nimble.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
Labels: Type: bug, Type: enhancement, Platform: ESP32

#2363 Fix access check code for memory mapped devices
  src/CLR/Debugger/Debugger.cpp
  targets/win32/nanoCLR/Target_BlockStorage.cpp
Labels: Type: bug, Area: Common libs

#2364 Fix SerialPort.GetPortNames() on all platforms
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/nanoFramework.Device.Can/nf_device_can_native_nanoFramework_Device_Can_CanController.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Area: Targets

#2367 Make sure that only one async SPI transaction can be active before blocking
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
Labels: Type: enhancement, Breaking-change, Platform: ESP32

#2368 Fixed typo in variable name
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
Labels: Area: Config-and-Build, Platform: ESP32

#2370 Fix tweaking sdkconfig for XTAL26 option
  CMake/binutils.ESP32.cmake
Labels: Area: Config-and-Build

#2369 Added asynchronous transfer support to the SPI display interface
  src/nanoFramework.Graphics/Graphics/Displays/DisplayInterface.h
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ILI9342_320x240_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1331_94x64_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7735S_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
Labels: Type: enhancement, Area: Common libs

#2371 Forcing UI SPI transfers to be synchronous
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
Labels: Type: enhancement

#2373 Added SPI interface method to wait on any outstanding async transfers
  src/HAL/Include/nanoHAL_Spi.h
  src/PAL/Include/CPU_SPI_decl.h
  src/System.Device.Spi/nanoHAL_Spi.cpp
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
Labels: Type: enhancement, Area: Common libs

#2377 Re-enable async display writes
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
Labels: Type: enhancement, Area: Common libs

#2378 Fix allocation of graphics heap memory
  targets/ESP32/ESP32/nanoCLR/nanoFramework.Graphics/Graphics_Memory.cpp
Labels: Type: bug, Platform: ESP32

#2388 Fix case in including headers
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/nanoFramework.Graphics/DSI_To_Display_Video_Mode.cpp
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/nanoFramework.Graphics/I2C_To_TouchPanel.cpp
Labels: Area: Config-and-Build, Area: Dev-Containers
