Repository nanoframework/nf-interpreter, pull requests merged in 2022-09, with the labels that each got.

#2426 Fix detection of Azure build to fix IDF build
  CMake/binutils.ESP32.cmake
Labels: Area: Config-and-Build

#2427 Fix IDF detection for dirty repo
  CMake/binutils.ESP32.cmake
  targets/ESP32/CMakeLists.txt
Labels: Area: Config-and-Build, Platform: ESP32

#2417 Add missing SDK Config to enable Bluetooth Nimble Central Mode for ESP32 REV3 hardware
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
Labels: Area: Config-and-Build, Platform: ESP32

#2429 Fix IDF bootloader banner
  CMake/ESP32_target_os.h.in
  CMake/binutils.ESP32.cmake
  bootloader_components/nf_boot_message/CMakeLists.txt
  bootloader_components/nf_boot_message/boot_msg.c
  targets/ESP32/CMakeLists.txt
Labels: Area: Config-and-Build, Platform: ESP32

#2428 Allow scanning and connections at same time
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/esp32_nimble.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_ble.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEAdvertisementWatcher.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEDevice.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
Labels: invalid

#2430 Update declaration of System.Device.Gpio
  src/System.Device.Gpio/sys_dev_gpio_native.cpp
Labels: Type: dependencies

#2431 Remove LTO options from all build and linker options
  CMake/Modules/AzureRTOS_MAX78000_GCC_options.cmake
  CMake/Modules/AzureRTOS_MICROBIT_GCC_options.cmake
  CMake/Modules/AzureRTOS_RP2040_GCC_options.cmake
  CMake/Modules/AzureRTOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/FreeRTOS_IMXRT10xx_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC13X2_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_GCC_options.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
  targets/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/ChibiOS/ST_NUCLEO64_F091RC/common/Device_BlockStorage.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/STM32F091xC_booter.ld
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/STM32F091xC_CLR.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/common/Device_BlockStorage.c
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/STM32F429xI_booter.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/STM32F429xI_CLR.ld
Labels: Area: Config-and-Build

#2432 Add back LTO
  CMake/Modules/AzureRTOS_MAX78000_GCC_options.cmake
  CMake/Modules/AzureRTOS_MICROBIT_GCC_options.cmake
  CMake/Modules/AzureRTOS_RP2040_GCC_options.cmake
  CMake/Modules/AzureRTOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/AzureRTOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F4xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32H7xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L0xx_GCC_options.cmake
  CMake/Modules/CHIBIOS_STM32L4xx_GCC_options.cmake
  CMake/Modules/FreeRTOS_IMXRT10xx_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC13X2_GCC_options.cmake
  CMake/Modules/TI_SimpleLink_CC32xx_GCC_options.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
  src/CLR/Core/CLR_RT_HeapBlock_Lock.cpp
  targets/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/ChibiOS/ST_NUCLEO64_F091RC/common/Device_BlockStorage.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/STM32F091xC_booter.ld
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/STM32F091xC_CLR.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/common/Device_BlockStorage.c
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/STM32F429xI_booter.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/STM32F429xI_CLR.ld
Labels: Area: Config-and-Build

#2433 Update declaration for Serial.IO.Ports
  src/System.IO.Ports/sys_io_ser_native.cpp
  src/System.IO.Ports/sys_io_ser_native.h
Labels: Type: dependencies

#2434 Fixes in System.IO.Port
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: bug, Series: STM32xx, Platform: Azure-RTOS

#2435 Update declaration for System.Device.Gpio
  src/System.Device.Gpio/sys_dev_gpio_native.cpp
  src/System.Device.Gpio/sys_dev_gpio_native.h
Labels: Type: dependencies

#2437 Update toolchain.arm-none-eabi.cmake
  CMake/toolchain.arm-none-eabi.cmake
Labels: Type: bug, Type: enhancement, Area: Config-and-Build

#2439 Fix ObjectsEqual
  src/CLR/Core/CLR_RT_HeapBlock.cpp
Labels: Type: bug, Area: Interpreter

#2365 Add support for other ESP32 ethernet boards
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindNF_Network.cmake
  CMake/binutils.ESP32.cmake
  CMakePresets.json
  CMakeUserPresets.TEMPLATE.json
  src/PAL/Lwip/lwIP_Sockets.cpp
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_Network/CMakeLists.txt
  targets/ESP32/_Network/NF_ESP32_Ethernet.cpp
  targets/ESP32/_Network/esp32_ethernet_options.h.in
  targets/ESP32/_common/targetHAL_Network.cpp
Labels: Type: bug, Type: enhancement, Area: Config-and-Build

#2444 Fix dealing with array types when getting method parameters
  src/CLR/CorLib/corlib_native_System_Reflection_MethodBase.cpp
Labels: Type: bug, Area: Interpreter
