Repository nanoframework/nf-interpreter, pull requests merged in 2022-08, with the labels that each got.

#2404 Fix ChibiOS HAL path for dev containers
  CMakeUserPresets.TEMPLATE.json
Labels: Area: Dev-Containers

#2405 Add flags to support 128 and 256 bit word flash architectures
  src/PAL/Include/nanoPAL_BlockStorage.h
Labels: Type: enhancement

#2406 Move ByteTime field to SPI_DEVICE_CONFIGURATION
  src/HAL/Include/nanoHAL_Spi.h
  src/PAL/Include/CPU_SPI_decl.h
  src/System.Device.Spi/nanoHAL_Spi.cpp
  src/System.Device.Spi/sys_dev_spi_native_System_Device_Spi_SpiDevice.cpp
Labels: Type: enhancement, Area: Common libs

#2407 Fix for Bitmap resources
  src/nanoFramework.Graphics/Graphics/Core/Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Core/Graphics.h
  src/nanoFramework.Graphics/Graphics/Core/Support/Bmp/Bitmap_Decoder.cpp
Labels: Type: bug, Area: Common libs

#2410 Fix inclusion of Azure RTOS user config file
  CMake/Modules/AzureRTOS_MAX78000_GCC_options.cmake
  CMake/Modules/AzureRTOS_MICROBIT_GCC_options.cmake
  CMake/Modules/AzureRTOS_RP2040_GCC_options.cmake
  CMake/Modules/AzureRTOS_STM32F7xx_GCC_options.cmake
  CMake/Modules/AzureRTOS_STM32L4xx_GCC_options.cmake
  CMake/binutils.AzureRTOS.cmake
  targets/AzureRTOS/CMakeLists.txt
  targets/AzureRTOS/Maxim/MAX78000_FTHR/CMakeLists.txt
  targets/AzureRTOS/MicroBit/MICRO_BIT_2/CMakeLists.txt
  targets/AzureRTOS/RaspberryPi/RPI_PICO/CMakeLists.txt
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/CMakeLists.txt
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/CMakeLists.txt
  targets/AzureRTOS/_common/include/targetHAL.h
Labels: Area: Config-and-Build, Platform: Azure-RTOS

#2374 Update fatfs to R14b
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/ffconf.h
  targets/ChibiOS/CMakeLists.txt
  targets/ChibiOS/ORGPAL_PALTHREE/ffconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/ffconf.h
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/FreeRTOS/NXP/_fatfs/ffconf.h
Labels: Type: enhancement, Area: Config-and-Build, Area: Targets, Type: dependencies, Area: Dev-Containers

#2409 Initial Bluetooth LE Central/Client implementation
  CMake/Modules/FindnanoFramework.Device.Bluetooth.cmake
  src/CLR/Include/nanoCLR_Hardware.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/esp32_nimble.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_ble.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEAdvertisementWatcher.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEDevice.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattReadRequest.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattServiceProvider.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattWriteRequest.cpp
Labels: Type: enhancement, Platform: ESP32

#2415 Update .gitignore to filter out vscode logs
  .gitignore
Labels: Area: Config-and-Build

#2412 ILI9341 universal display driver update
  CMakePresets.json
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_XXXxYYY_SPI.cpp
Labels: Type: bug, Type: enhancement, Area: Config-and-Build

#2414 Add FillRectangle function to display driver
  src/nanoFramework.Graphics/Graphics/Core/Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Core/Graphics.h
  src/nanoFramework.Graphics/Graphics/Core/GraphicsDriver.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
Labels: Type: bug, Type: enhancement

#2413 Fix NativeChangeOrientation
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
Labels: Type: bug, Area: Common libs

#2418 Fix sending empty string over SerialPort
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort__.cpp
Labels: Type: bug, Area: Common libs

#2419 Fix initialization of HAL drivers in all platforms
  targets/AzureRTOS/Maxim/_nanoCLR/targetHAL.cpp
  targets/AzureRTOS/ST/_nanoCLR/targetHAL.cpp
  targets/ChibiOS/_nanoCLR/targetHAL.cpp
  targets/TI_SimpleLink/_nanoCLR/targetHAL.cpp
Labels: Type: enhancement, Platform: STM32, Platform: NXP, Platform: Azure-RTOS

#2420 Update mbedtls to v2.28.1
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/Dockerfile.ESP32
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  targets/ChibiOS/CMakeLists.txt
Labels: Type: dependencies, Area: Dev-Containers

#2421 Migrate Espressif IDF to v4.4.2
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.ESP32
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ESP32
  .vscode/tasks.TEMPLATE.json
  CMake/binutils.ESP32.cmake
  azure-pipelines-nightly.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines.yml
  targets/ESP32/CMakeLists.txt
Labels: Status: in progress, Area: Config-and-Build, Area: Dev-Containers

#2416 Update ARM GCC to 11.3.Rel1
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/Dockerfile.TI
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.TI
  CMake/Modules/AzureRTOS_STM32L4xx_GCC_options.cmake
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  install-scripts/install-arm-gcc-toolchain.ps1
Labels: Type: dependencies, Area: Dev-Containers

#2422 Add Rtc SetSystemTime implementation for ST in Azure RTOS
  targets/AzureRTOS/ST/_nanoCLR/CMakeLists.txt
  targets/AzureRTOS/ST/_nanoCLR/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Native_Rtc.cpp
Labels: Type: enhancement, Series: STM32xx, Platform: Azure-RTOS

#2423 Improve adding RTC native source file
  CMake/Modules/FindNF_CoreCLR.cmake
  targets/AzureRTOS/ST/_nanoCLR/CMakeLists.txt
  targets/ChibiOS/_nanoCLR/CMakeLists.txt
  targets/ESP32/_nanoCLR/CMakeLists.txt
  targets/FreeRTOS/NXP/_nanoCLR/CMakeLists.txt
  targets/TI_SimpleLink/_nanoCLR/CMakeLists.txt
Labels: Area: Config-and-Build

#2424 Work CI-CD
  CMakeLists.txt
Labels: Area: Config-and-Build
