Repository nanoframework/nf-interpreter, pull requests merged in 2022-05, with the labels that each got.

#2298 Fix lwIP driver for GetAddrInfo
  src/PAL/Lwip/lwIP_Sockets.cpp
Labels: Type: enhancement, RTOS: ChibiOS

#2299 Fix GPIO pins reservation for PSRAM
  targets/ESP32/_nanoCLR/System.Device.Gpio/cpu_gpio.cpp
Labels: Type: enhancement, RTOS: ESP32

#2301 Improvements in GPIO reservation for PSRAM
  targets/ESP32/_nanoCLR/System.Device.Gpio/cpu_gpio.cpp
Labels: Type: enhancement, RTOS: ESP32

#2302 Fix WiFi assembly declaration
  src/System.Device.WiFi/sys_dev_wifi_native.cpp
  src/System.Device.WiFi/sys_dev_wifi_native.h
Labels: Area: Config-and-Build

#2303 Update sys.dev.wifi declarations
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindSystem.Device.WiFi.cmake
  CMake/Modules/FindSystem.Device.Wifi.cmake
  CMakePresets.json
  src/PAL/Include/nanoPAL_Sockets.h
  src/System.Device.Wifi/sys_dev_wifi_native.cpp
  src/System.Device.Wifi/sys_dev_wifi_native.h
  targets/ESP32/_nanoCLR/System.Device.Wifi/sys_dev_wifi_native_System_Device_Wifi_WifiAdapter.cpp
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/README.md
Labels: Area: Config-and-Build, Breaking-change

#2304 Fix compile options for debug builds
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.ESP32.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.TI_SimpleLink.cmake
Labels: Area: Config-and-Build

#2297 Fix Flash erase in FlashV2
  targets/ChibiOS/_nf-overlay/os/hal/ports/STM32/LLD/FLASHv2/flash_lld.c
Labels: Type: bug, RTOS: ChibiOS

#2305 Improvements in toolchain handling
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/Dockerfile.ESP32
  .devcontainer/Dockerfile.TI
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.TI
  .vscode/cmake-variants.TEMPLATE.json
  CMake/binutils.TI_SimpleLink.cmake
  CMake/binutils.arm-none-eabi.cmake
  CMake/toolchain.arm-none-eabi.cmake
  CMakeLists.txt
  CMakeUserPresets.TEMPLATE.json
  azure-pipelines-nightly.yml
  azure-pipelines-templates/build-chibios-stm32.yml
  azure-pipelines-templates/build-freertos-nxp.yml
  azure-pipelines-templates/build-ti-simplelink.yml
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines.yml
  install-scripts/configure-vscode-common.psm1
  install-scripts/install-arm-gcc-toolchain.ps1
  targets/FreeRTOS/NXP/NXP_MIMXRT1060_EVK/README.md
Labels: Type: documentation, Area: Config-and-Build, Area: Dev-Containers

#2307 Fix SPIFFS implementation
  targets/ChibiOS/_spiffs/hal_spiffs.c
  targets/ChibiOS/_spiffs/hal_spiffs.h
Labels: Type: bug, RTOS: ChibiOS

#2311 Wifi task is now pinned to core 1
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Area: Config-and-Build, RTOS: ESP32

#2312 Fix include order for Mbed TLS in ESP32
  CMake/Modules/FindNF_Network.cmake
  CMake/binutils.common.cmake
  src/PAL/COM/sockets/ssl/mbedTLS/mbedtls.h
  targets/ESP32/ESP32/launch.json
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Type: bug, Area: Config-and-Build, RTOS: ESP32

#2315 Fix core assignments (again)
  targets/ESP32/_IDF/esp32/app_main.c
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
Labels: Area: Config-and-Build, RTOS: ESP32

#2308 Fix RingBuffer OptimizeSequence
  src/HAL/Include/nanoHAL.h
Labels: Type: bug, Status: in progress

#2316 Fixes incorrect files name casing in cmake
  CMake/Modules/FindSystem.Device.Spi.cmake
  CMake/Modules/FindSystem.Device.Wifi.cmake
Labels: Area: Config-and-Build

#2317 Fix definition for HeapBegin
  targets/ChibiOS/_common/rules_clr.ld
  targets/TI_SimpleLink/_common/rules_clr.ld
Labels: Area: Config-and-Build, RTOS: ChibiOS, RTOS: TI-SimpleLink

#2318 GC pressure thresholds now have defaults dependent on heap size
  src/CLR/Core/CLR_RT_Memory.cpp
  src/CLR/Include/nanoCLR_PlatformDef.h
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Type: enhancement, Area: Interpreter

#2321 Hostname truncated
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_include/lwipopts.h
Labels: Type: bug, Area: Config-and-Build, RTOS: ESP32

#2319 Enable 1-Wire for ESP32 targets
  CMakePresets.json
Labels: Area: Config-and-Build

#2322 Fix 1-Wire constructor to allow reuse
  targets/ESP32/_nanoCLR/nanoFramework.Device.OneWire/nf_dev_onewire_nanoFramework_Device_OneWire_OneWireHost.cpp
Labels: Type: bug, RTOS: ESP32

#2323 Rename Devices.Can to Device.Can
  .vscode/cmake-variants.TEMPLATE.json
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindnanoFramework.Device.Can.cmake
  CMake/Modules/FindnanoFramework.Devices.Can.cmake
  CMakeLists.txt
  CMakePresets.json
  src/nanoFramework.Device.Can/nf_device_can_native.cpp
  src/nanoFramework.Device.Can/nf_device_can_native.h
  src/nanoFramework.Devices.Can/nf_devices_can_native.cpp
  src/nanoFramework.Devices.Can/nf_devices_can_native.h
  targets/ChibiOS/ORGPAL_PALTHREE/target_nf_devices_can_config.cpp
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_device_can_config.cpp
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/target_nf_device_can_config.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_device_can_config.cpp
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_nf_device_can_config.h
  targets/ChibiOS/_nanoCLR/nanoFramework.Device.Can/nf_device_can_native_nanoFramework_Device_Can_CanController.cpp
  targets/ChibiOS/_nanoCLR/nanoFramework.Device.Can/nf_device_can_native_target.h
  targets/ChibiOS/_nanoCLR/targetHAL.cpp
Labels: Area: Config-and-Build, Breaking-change

#2324 Fix hang in nanoClr when using serial with Hand shake is enabled
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, RTOS: ESP32

#2336 Typo in Cmakepresets.json
  CMakePresets.json
Labels: Type: bug, Area: Config-and-Build, Platform: ESP32

#2335 Update CI VM images to `windows-latest`
  azure-pipelines-nightly.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#2334 Code comment fixes
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: documentation

#2337 Restarts firmware when ethernet driver fails to install
  targets/ESP32/_Network/NF_ESP32_Ethernet.cpp
Labels: Type: bug, Platform: ESP32

#2327 Cmake Presets improvements
  CMakePresets.json
  CMakeUserPresets.TEMPLATE.json
Labels: Area: Config-and-Build

#2338 Fixes and improvements in X.509 parsing
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_SslNative.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Security_Cryptography_X509Certificates_X509Certificate.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Security_Cryptography_X509Certificates_X509Certificate2.cpp
Labels: Type: enhancement

#2339 Update declaration of Esp32.Rmt
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native.h
Labels: Type: dependencies

#2342 Update SSL code parsing X.509 certificates
  src/DeviceInterfaces/System.Net/sys_net_native.cpp
  src/DeviceInterfaces/System.Net/sys_net_native.h
  src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Security_SslNative.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Security_Cryptography_X509Certificates_X509Certificate.cpp
  src/DeviceInterfaces/System.Net/sys_net_native_System_Security_Cryptography_X509Certificates_X509Certificate_stubs.cpp
  src/PAL/COM/sockets/Sockets_debugger.cpp
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_add_cert_auth_internal.cpp
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_generic_init_internal.cpp
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_parse_certificate_internal.cpp
  src/PAL/COM/sockets/ssl/ssl.cpp
  src/PAL/COM/sockets/ssl/ssl_functions.h
  src/PAL/COM/sockets/ssl/ssl_stubs.cpp
  src/PAL/Include/nanoPAL_Sockets.h
Labels: Type: dependencies

#2344 Update System.IO.Ports declaration
  src/System.IO.Ports/sys_io_ser_native.cpp
Labels: Type: dependencies

#2345 WatchChar is not set on SerialPort init
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: STM32, Platform: ESP32, Platform: NXP, Platform: TI-SimpleLink

#2347 Fix IsInstanceOf when comparing arrays
  src/CLR/Core/Execution.cpp
Labels: Type: bug, Area: Interpreter

#2346 Add implementation for SerialPort ReceivedBytesThreshold
  src/System.IO.Ports/sys_io_ser_native.cpp
  src/System.IO.Ports/sys_io_ser_native.h
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort_stubs.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_target.h
Labels: Type: enhancement, Area: Common libs, Platform: STM32, Platform: ESP32, Platform: NXP, Platform: TI-SimpleLink

#2348 Fix boxing in custom attributes
  src/CLR/Core/TypeSystem.cpp
Labels: Type: bug, Area: Interpreter

#2349 Improve generation of deviceSelectorString for several drivers
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/nanoFramework.Device.Can/nf_device_can_native_nanoFramework_Device_Can_CanController.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: enhancement, Platform: STM32, Platform: ESP32, Platform: TI-SimpleLink

#2350 Miscellaneous fixes in runtime
  src/CLR/Core/CLR_RT_RuntimeMemory.cpp
  src/CLR/Core/CLR_RT_StackFrame.cpp
  src/CLR/Core/Cache.cpp
  src/CLR/Core/Execution.cpp
  src/CLR/Core/GarbageCollector.cpp
  src/CLR/Core/Interpreter.cpp
  src/CLR/Core/Thread.cpp
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/nanoCLR_Runtime.h
  src/CLR/Include/nanoCLR_Types.h
  targets/win32/nanoCLR/Generated/CLR_RT_InteropAssembliesTable.cpp
Labels: Area: Config-and-Build
