Repository nanoframework/nf-interpreter, pull requests merged in 2023-01, with the labels that each got.

#2508 Update ChibiOS HAL for v8.4
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/nanoBooter/halconf.h
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/nanoCLR/halconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/halconf.h
  targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/halconf.h
  targets/ChibiOS/ORGPAL_PALTHREE/nanoBooter/halconf.h
  targets/ChibiOS/ORGPAL_PALTHREE/nanoCLR/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/halconf.h
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoBooter/halconf.h
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/halconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/halconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf.h
Labels: Type: dependencies

#2507 Fix base path for include and search in CMake modules
  CMake/Modules/FindSystem.Device.Adc.cmake
  CMake/Modules/FindSystem.Device.Pwm.cmake
  CMake/Modules/FindSystem.Device.Wifi.cmake
  CMake/Modules/FindSystem.IO.FileSystem.cmake
  CMake/Modules/FindSystem.IO.Ports.cmake
  CMake/Modules/FindSystem.Runtime.Serialization.cmake
  CMake/Modules/FindnanoFramework.Device.Bluetooth.cmake
Labels: Area: Config-and-Build

#2509 Increase IDF reserved memory for ESP32 PICO
  CMakePresets.json
Labels: Area: Config-and-Build

#2505 Add more program widths in block storage attributes
  src/PAL/Include/nanoPAL_BlockStorage.h
Labels: Type: enhancement

#2511 Update Mbed TLS to 2.28.2
  .devcontainer/Dockerfile.All
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  CMake/Modules/FindMbedTLS.cmake
  CMake/Modules/FindNF_Network.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.ESP32.cmake
  CMake/binutils.common.cmake
  CMakeLists.txt
  src/CLR/Helpers/Base64/base64.c
  src/CLR/Helpers/Base64/base64.h
  src/PAL/COM/sockets/ssl/MbedTLS/mbedtls.h
  src/PAL/COM/sockets/ssl/MbedTLS/nf_mbedtls_config.h
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_accept_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_add_cert_auth_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_available_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_close_socket_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_connect_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_decode_private_key_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_exit_context_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_generic.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_generic_init_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_initialize_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_parse_certificate_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_read_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_uninitialize_internal.cpp
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_write_internal.cpp
  src/PAL/COM/sockets/ssl/mbedTLS/ssl_generic.cpp
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/mbedtls_config.h
  targets/ChibiOS/CMakeLists.txt
  targets/ChibiOS/ORGPAL_PALTHREE/mbedtls_config.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/mbedtls_config.h
  targets/ESP32/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/TI_SimpleLink/_common/ssl_simplelink.cpp
  targets/win32/nanoCLR/base64.cpp
Labels: Area: Config-and-Build, Type: dependencies, Area: Dev-Containers

#2514 Enable System.IO.FileSystem for ESP32_S2 targets
  CMakePresets.json
  targets/ESP32/_include/esp32_idf.h
Labels: Area: Config-and-Build, Platform: ESP32, Series: ESP32S2

#2325 Add support for LCD in ST_STM32F429I_DISCOVERY
  CMakePresets.json
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
  src/nanoFramework.Graphics/TouchPanel/Devices/STMPE811QTR_I2C.cpp
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/STM32F429xI_CLR-DEBUG.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/STM32F429xI_CLR.ld
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/halconf_nf.h
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/nanoFramework.Graphics/Graphics_Memory.cpp
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/nanoFramework.Graphics/I2C_To_TouchPanel.cpp
  targets/ChibiOS/ST_STM32F429I_DISCOVERY/nanoCLR/nanoFramework.Graphics/Spi_To_TouchPanel.cpp
Labels: Type: enhancement, Platform: STM32

#2515 Rework HAL Time implementations
  CMake/binutils.FreeRTOS.cmake
  src/CLR/WireProtocol/targetHAL_time.cpp
  src/HAL/Include/nanoHAL_Time.h
  targets/AzureRTOS/ChibiOS/osal.h
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/nanoBooter/chconf.h
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/nanoCLR/chconf.h
  targets/AzureRTOS/ST/_include/targetHAL_Time.h
  targets/AzureRTOS/_common/targetHAL_Time.cpp
  targets/ChibiOS/ORGPAL_PALTHREE/nanoBooter/chconf.h
  targets/ChibiOS/ORGPAL_PALTHREE/nanoCLR/chconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/chconf.h
  targets/ChibiOS/_common/targetHAL_Time.cpp
  targets/ChibiOS/_include/targetHAL_Time.h
  targets/ESP32/_common/targetHAL_Time.cpp
  targets/ESP32/_include/targetHAL_Time.h
  targets/FreeRTOS/_common/include/targetHAL_Time.h
  targets/FreeRTOS/_common/include/targetPAL_Time.h
  targets/FreeRTOS/_common/targetHAL_Time.cpp
  targets/TI_SimpleLink/_common/platformHAL_Time.cpp
  targets/TI_SimpleLink/_include/targetHAL_Time.h
Labels: Type: enhancement, Area: Common libs, Platform: STM32, Platform: ESP32, Platform: NXP, Platform: TI-SimpleLink, Platform: Azure-RTOS

#2516 Fix SysTicksToTime
  targets/ESP32/_include/targetHAL_Time.h
  targets/FreeRTOS/_common/include/targetHAL_Time.h
Labels: Type: bug, Platform: ESP32, Platform: NXP

#2521 Add support for STM32 configuration
  CMake/Modules/FindnanoFramework.Hardware.Stm32.cmake
  targets/ChibiOS/_nanoCLR/System.Device.Adc/sys_dev_adc_native_System_Device_Adc_AdcChannel.cpp
  targets/ChibiOS/_nanoCLR/System.Device.Adc/sys_dev_adc_native_System_Device_Adc_AdcController.cpp
  targets/ChibiOS/_nanoCLR/System.Device.Adc/sys_dev_adc_native_target.h
  targets/ChibiOS/_nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.cpp
  targets/ChibiOS/_nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native.h
  targets/ChibiOS/_nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native_nanoFramework_Hardware_Stm32_Configuration.cpp
Labels: Type: enhancement, Type: dependencies, Platform: STM32

#2526 Fix build of TI targets with Sys.IO.SerialPort
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: TI-SimpleLink

#2518 Fixes multiple devices on same SPI bus
  .devcontainer/devcontainer.json
  src/DeviceInterfaces/Network/Enc28j60/enc28j60_lwip.cpp
  src/PAL/Include/CPU_SPI_decl.h
  src/System.Device.Spi/nanoHAL_Spi.cpp
  src/System.Device.Spi/sys_dev_spi_native_System_Device_Spi_SpiDevice.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Spi_To_Display.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.Spi/sys_dev_spi_native_target.h
  targets/ChibiOS/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/ChibiOS/_nanoCLR/System.Device.Spi/sys_dev_spi_native_target.h
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/ESP32/_nanoCLR/System.Device.Spi/sys_dev_spi_native_target.h
Labels: Type: bug

#2529 Fix check for TI-RTOS sys config file
  CMake/binutils.TI_SimpleLink.cmake
Labels: Area: Config-and-Build

#2530 Improvements in build artifacts generation
  CMake/binutils.arm-none-eabi.cmake
  CMake/binutils.common.cmake
  azure-pipelines-templates/pack-publish-artifacts.yml
Labels: Area: Config-and-Build

#2531 Fixes SPI with 3 devices on 1 SPI bus for ESP32 devices
  src/System.Device.Spi/nanoHAL_Spi.cpp
Labels: Type: bug, Platform: ESP32
