Repository nanoframework/nf-interpreter, pull requests merged in 2023-11, with the labels that each got.

#2805 Fix dataWidth check for ESP32 MMC to enable 4-bit access
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_nanoFramework_System_IO_FileSystem_SDCard.cpp
  targets/ESP32/_nanoCLR/Windows.Storage/win_storage_native_Windows_Storage_Devices_SDCard.cpp
Labels: Type: bug, Platform: ESP32

#2807 Update MBED TLS for Dockerfile.ChibiOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ChibiOS
Labels: Area: Config-and-Build

#2808 Fix build issue with GCC 13.2.rel1
  src/CLR/CorLib/corlib_native_System_Number.cpp
Labels: Type: enhancement, Area: Common libs

#2724 Update FatFs to R0.15
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  CMake/Modules/FindCHIBIOS_FATFS.cmake
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/ffconf.h
  targets/ChibiOS/CMakeLists.txt
  targets/ChibiOS/ORGPAL_PALTHREE/ffconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/ffconf.h
  targets/ChibiOS/_FatFS/fatfs_syscall.c
  targets/FreeRTOS/NXP/CMakeLists.txt
  targets/FreeRTOS/NXP/_fatfs/ffconf.h
  targets/FreeRTOS/NXP/_fatfs/ffsystem.c
Labels: Area: Config-and-Build, Type: dependencies

#2813 Update Azure RTOS to v6.3.0
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  targets/AzureRTOS/CMakeLists.txt
Labels: Area: Config-and-Build, Type: dependencies, Platform: Azure-RTOS, Area: Dev-Containers

#2814 Update Gecko SDK to v4.3.2
  CMake/Modules/FindGecko_SDK.cmake
  targets/AzureRTOS/SiliconLabs/CMakeLists.txt
Labels: Type: dependencies, Series: SL-EFM32GG11

#2817 Add asserts and debug output helpers to GC
  src/CLR/Core/Execution.cpp
  src/CLR/Core/GarbageCollector_Compaction.cpp
  src/CLR/Core/GarbageCollector_Info.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Type: enhancement, Area: Common libs

#2818 Fix GC handling string heap block
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Core/CLR_RT_HeapBlock_String.cpp
Labels: Type: bug, Type: enhancement

#2819 Add dummy implementation of sli_sleeptimer_hal_power_manager_integration_init
  targets/AzureRTOS/SiliconLabs/_common/sl_sleeptimer_.c
Labels: Area: Config-and-Build, Series: SL-EFM32GG11

#2820 Hard fault caused by unaligned Memory Access on STM32F769 series
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/target_external_memory.c
Labels: Type: bug, Platform: STM32

#2821 Fix access to env var in CMake
  CMake/toolchain.arm-none-eabi.cmake
Labels: Area: Config-and-Build

#2822 Use only 32-bit ARGB or RGB565 formats
  src/nanoFramework.Graphics/Graphics/Core/Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Core/Graphics.h
  src/nanoFramework.Graphics/Graphics/Core/GraphicsDriver.cpp
  src/nanoFramework.Graphics/Graphics/Core/Support/Bmp/Bitmap_Decoder.cpp
  src/nanoFramework.Graphics/Graphics/Core/Support/Gif/Gif.cpp
  src/nanoFramework.Graphics/Graphics/Core/Support/Gif/GifDecoder.cpp
  src/nanoFramework.Graphics/Graphics/Core/Support/Jpeg/Jpeg.cpp
  src/nanoFramework.Graphics/Graphics/Displays/DisplayInterface.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Bitmap.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Ink.cpp
  src/nanoFramework.Graphics/TouchPanel/Core/Ink.cpp
  src/nanoFramework.Graphics/TouchPanel/Core/Ink.h
Labels: Type: enhancement, Area: Common libs, Breaking-change

#2802 Updating Graphics signatures
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
Labels: Type: dependencies

#2823 Update `System.IO.File` declaration
  src/System.IO.FileSystem/nf_sys_io_filesystem.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem.h
Labels: Type: dependencies

#2810 Improve min max performance and IEEE compliance
  src/CLR/System.Math/nf_native_system_math.cpp
  src/CLR/System.Math/nf_native_system_math.h
  src/CLR/System.Math/nf_native_system_math_System_Math.cpp
Labels: Type: bug, Type: enhancement, Area: Common libs

#2815 Switching MathInternal.Min/Max to managed implementations
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_MathInternal.cpp
Labels: Type: enhancement, Area: Common libs, Type: dependencies

#2826 Adding check for zero length string
  src/CLR/CorLib/corlib_native_System_String.cpp
Labels: Type: bug, Area: Common libs

#2828 Enable I2C Slave to most ESP32 targets
  CMake/xtensa-esp32.json
  CMake/xtensa-esp32c3.json
  CMake/xtensa-esp32s2.json
  CMake/xtensa-esp32s3.json
  targets/ESP32/CMakePresets.json
Labels: Area: Config-and-Build, Platform: ESP32

#2790 Make ChibiOS lwIP platform independent
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ChibiOS
  CMake/Modules/FindCHIBIOS_LWIP.cmake
  config/user-tools-repos.TEMPLATE.json
  targets/ChibiOS/CMakeLists.txt
  targets/FreeRTOS/NXP/CMakeLists.txt
Labels: Area: Config-and-Build

#2791 Update ChibiOS lwip to 2.1.3
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ChibiOS
  targets/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build, Type: dependencies, Platform: STM32

#2827 Updating `System.IO.Path` signature
  src/System.IO.FileSystem/nf_sys_io_filesystem.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem.h
Labels: Type: dependencies

#2825 Improve Dockerfiles
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/Dockerfile.ESP32
  .devcontainer/Dockerfile.TI
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.ESP32
  .devcontainer/sources/Dockerfile.TI
  .github/workflows/devcontainer-smoketest.yaml
  config/user-tools-repos.TEMPLATE.json
Labels: Area: Dev-Containers

#2833 Fix serial parity and databits for STM32
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: STM32

#2834 Fix UART configuration to handle length, parity and stop bits
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: STM32

#2835 Fix memory leak with serial port WriteString
  azure-pipelines.yml
  targets/AzureRTOS/ST/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/FreeRTOS/NXP/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
  targets/TI_SimpleLink/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: STM32, Platform: ESP32, Platform: NXP, Platform: TI-SimpleLink, Platform: Azure-RTOS
