Repository nanoframework/nf-interpreter, pull requests merged in 2023-07, with the labels that each got.

#2690 Correct directory variables for Azure RTOS build
  targets/AzureRTOS/CMakeLists.txt
Labels: Type: bug, Area: Config-and-Build

#2693 Fix SDK config for not including certificate bundle
  targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32
  targets/ESP32/_IDF/sdkconfig.default.esp32c3
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default.esp32s3
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32s3
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_pico_ble_rev3
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32c3
  targets/ESP32/_IDF/sdkconfig.default_rev3_noconsole.esp32c3
Labels: Area: Config-and-Build, Platform: ESP32

#2695 Rework task creation for ESP32-S3
  targets/ESP32/_IDF/esp32s3/app_main.c
Labels: Type: bug, Platform: ESP32, Series: ESP32S3

#2696 Work on ESP32S3 build system
  CMake/Modules/FindESP32_IDF.cmake
  azure-pipelines-nightly.yml
  targets/ESP32/CMakePresets.json
  targets/ESP32/_IDF/sdkconfig.default.esp32s3
Labels: Area: Config-and-Build, Platform: ESP32, Series: ESP32S3

#2697 Fixing dev containers regarding Python version
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ESP32
Labels: Area: Dev-Containers

#2698 Add garbage collector info to nanoCLR
  src/CLR/Core/Core.vcxproj
  src/CLR/Core/Core.vcxproj.filters
Labels: Area: Config-and-Build, Platform: Virtual Device & WIN32

#2700 Fix Esp32 Dev Container Python Path
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ESP32
Labels: Type: bug

#2699 Fix buffer overflow error on GC
  src/CLR/Core/GarbageCollector_ComputeReachabilityGraph.cpp
Labels: Type: bug, Area: Interpreter

#2702 Fix types on several locals
  src/CLR/Core/GarbageCollector.cpp
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.cpp
Labels: Type: enhancement

#2701 Fix function not returning value on all paths
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.cpp
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#2703 Improve HeapCluster_Initialize
  src/CLR/Core/CLR_RT_HeapCluster.cpp
Labels: Type: enhancement, Area: Common libs

#2704 Fix debug output for heap allocation
  src/CLR/Core/Execution.cpp
Labels: Type: enhancement, Area: Common libs

#2705 Fix computation of GC reachability for arrays with referenced objects
  src/CLR/Core/GarbageCollector_ComputeReachabilityGraph.cpp
Labels: Type: bug, Area: Common libs

#2706 Fix relocation of heap block array
  src/CLR/Core/CLR_RT_HeapBlock_Array.cpp
Labels: Type: bug, Area: Common libs

#2707 Fix GC recursive crawling of arrays with referenced objects
  src/CLR/Core/GarbageCollector_ComputeReachabilityGraph.cpp
Labels: Type: bug, Area: Common libs

#2708 Enable watchdog for Gecko targets
  CMake/Modules/FindGecko_SDK.cmake
  targets/AzureRTOS/SiliconLabs/SL_STK3701A/nanoCLR/main.c
  targets/AzureRTOS/SiliconLabs/_nanoCLR/CMakeLists.txt
  targets/AzureRTOS/SiliconLabs/_nanoCLR/targetHAL_Power.c
  targets/AzureRTOS/SiliconLabs/_nanoCLR/targetHAL_Watchdog.c
Labels: Type: enhancement, Area: Config-and-Build, Series: SL-EFM32GG11

#2709 Add ESP32_USB_CDC option to ESP32 S3 BLE in CmakePresets
  targets/ESP32/CMakePresets.json
Labels: Area: Config-and-Build, Platform: ESP32

#2710 Revert recent changes in GC code
  src/CLR/Core/CLR_RT_HeapBlock_Array.cpp
  src/CLR/Core/GarbageCollector_ComputeReachabilityGraph.cpp
Labels: invalid

#2712 Fixing several build options for ESP32S3
  targets/ESP32/CMakePresets.json
  targets/ESP32/_IDF/sdkconfig.default.esp32s3
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32s3
Labels: Area: Config-and-Build, Series: ESP32S3

#2713 Increase reservation for IDF allocation
  targets/ESP32/CMakePresets.json
Labels: Area: Config-and-Build, Series: ESP32S3
