Repository nanoframework/nf-interpreter, pull requests merged in 2023-05, with the labels that each got.

#2651 Improve ChibiOS sys_io_ser_native_System_IO_Ports_SerialPort comments
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: documentation

#2654 Update STM32F769I README
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/README.md
Labels: Type: documentation

#2643 Update declaration of (new) Graphics library
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Bitmap.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
Labels: Type: dependencies

#2656 Fix CRC32 hardware calculation
  targets/ESP32/_common/nanoSupport_CRC32.c
Labels: Platform: ESP32

#2657 Replace implementation of nano printf
  src/CLR/CorLib/corlib_native_System_Number.cpp
  src/CLR/Helpers/nanoprintf/nanoprintf.c
  src/CLR/Helpers/nanoprintf/nanoprintf.h
Labels: Type: enhancement, Area: Common libs

#2658 Fix number Format for G and F format specifiers
  src/CLR/CorLib/corlib_native_System_Number.cpp
Labels: Type: bug, Area: Common libs

#2659 Add implementation for format specifier E
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Number.cpp
Labels: Type: enhancement, Area: Common libs

#2661 Add ILI9488_480x320_SPI Display driver
  src/nanoFramework.Graphics/Graphics/Displays/ILI9488_480x320_SPI.cpp
Labels: Type: enhancement, Area: Common libs

#2662 Replace nanoprintf with es-printf
  src/CLR/CorLib/corlib_native_System_Number.cpp
  src/CLR/Helpers/nanoprintf/nanoprintf.c
  src/CLR/Helpers/nanoprintf/nanoprintf.h
Labels: Type: enhancement

#2663 More fixes in Number.Format
  src/CLR/CorLib/corlib_native_System_Number.cpp
Labels: Type: bug, Area: Common libs

#2664 Fix SPI for ESP32-C3
  targets/ESP32/_nanoCLR/System.Device.Spi/cpu_spi.cpp
Labels: Type: bug

#2665 Fix SSL init
  src/PAL/COM/sockets/ssl/MbedTLS/ssl_generic_init_internal.cpp
Labels: Type: bug, Area: Common libs

#2666 Fix processing Wire Protocol header reception
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: bug, Area: Common libs

#2667 Add CPU_SPI_Initialize_Extended
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.Spi/sys_dev_spi_native_target.h
Labels: Type: enhancement, Platform: Azure-RTOS, Series: SL-EFM32GG11

#2669 Add option to boot to nanoBooter on CLR fault
  src/CLR/Include/nanoCLR_Application.h
  src/CLR/Startup/CLRStartup.cpp
Labels: Type: enhancement, Area: Common libs

#2670 Improvements in USB Stream
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.UsbStream/sys_dev_usbstream_native_System_Device_Usb_UsbStream.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.UsbStream/sys_dev_usbstream_native_target.h
Labels: Type: bug, Area: Common libs, Series: SL-EFM32GG11

#2671 Fix Messaging creation and destruction
  src/CLR/Messaging/Messaging.cpp
Labels: Type: bug, Area: Common libs

#2672 Add support for AZDO to run mscorlib unit tests on demand
  azure-pipelines.yml
  targets/netcore/pipeline_tests.runsettings
Labels: Area: Config-and-Build

#2673 Improve ObjectsEqual
  src/CLR/Core/CLR_RT_HeapBlock.cpp
Labels: Type: bug, Type: enhancement, Area: Common libs

#2674 Fix wrong exception reported on BinaryFormatter::Deserialize failure
  src/System.Runtime.Serialization/nf_system_runtime_serialization_System_Runtime_Serialization_Formatters_Binary_BinaryFormatter.cpp
Labels: Type: bug

#2675 Fix memory check
  src/CLR/Debugger/Debugger.cpp
Labels: Type: bug, Area: Common libs

#2676 Fix usb stream
  targets/AzureRTOS/SiliconLabs/README.md
  targets/AzureRTOS/SiliconLabs/SL_STK3701A/config/sl_usbd_device_config.h
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.UsbStream/sys_dev_usbstream_native_System_Device_Usb_UsbStream.cpp
Labels: Type: enhancement, Type: documentation, Series: SL-EFM32GG11

#2677 Add missing cast to number conversion
  src/CLR/CorLib/corlib_native_System_Number.cpp
Labels: Type: bug
