Repository nanoframework/nf-interpreter, pull requests merged in 2023-04, with the labels that each got.

#2613 Improve SNTP options
  src/DeviceInterfaces/Networking.Sntp/lwip_sntp_default_options.h
  targets/TI_SimpleLink/TI_CC3220SF_LAUNCHXL/target_sntp_opts.h
  targets/TI_SimpleLink/_include/targetSimpleLinkCC32xx_Sntp.h
Labels: Type: enhancement, Area: Common libs, Series: TI-CC32xx

#2620 Improvements Gecko boot
  targets/AzureRTOS/SiliconLabs/_nanoCLR/targetHAL.cpp
Labels: Type: bug, Type: enhancement, Series: SL-EFM32GG11

#2628 Fix output of version string in nanoCLR
  targets/netcore/nanoFramework.nanoCLR.CLI/Program.cs
Labels: Type: bug, Platform: Virtual Device & WIN32

#2629 Fix out of memory when no characteristics in service
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattServiceProvider.cpp
Labels: Type: bug

#2624 Fix ChibiOS F7 mcuconfig
  targets/ChibiOS/ORGPAL_PALTHREE/nanoBooter/mcuconf.h
  targets/ChibiOS/ORGPAL_PALTHREE/nanoCLR/mcuconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/mcuconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/mcuconf.h
Labels: Area: Config-and-Build, Platform: STM32

#2622 Add implementation for platform_heap realloc
  targets/ChibiOS/_common/platform_heap.c
Labels: Type: bug, Platform: STM32

#2583 Create .gitattributes
  .gitattributes
Labels: Type: enhancement, Area: Dev-Containers

#2632 Fixing ILI9341
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp
Labels: Type: bug

#2631 Adjusting container All for IDF 4.4.4
  .devcontainer/Dockerfile.All
  .devcontainer/sources/Dockerfile.All
Labels: Area: Dev-Containers

#2630 Signature changes due to Bluetooth purge scan fix
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
Labels: Type: bug

#2640 Remove platform_realloc
  src/HAL/Include/nanoHAL_v2.h
  targets/AzureRTOS/_common/platform_heap.c
  targets/ChibiOS/_common/platform_heap.c
  targets/ESP32/_common/platform_heap.c
  targets/FreeRTOS/_common/platform_heap.c
  targets/TI_SimpleLink/_common/platform_heap.c
  targets/win32/nanoCLR/platform_heap.cpp
Labels: Type: enhancement, Area: Common libs

#2603 Add XIAO_ESP32C3 and connect by built-in USB
  README.md
  README.zh-cn.md
  azure-pipelines-nightly.yml
  targets/ESP32/CMakeLists.txt
  targets/ESP32/CMakePresets.json
  targets/ESP32/_IDF/sdkconfig.default_rev3_noconsole.esp32c3
  targets/ESP32/_common/WireProtocol_HAL_Interface.c
  targets/ESP32/_nanoCLR/targetHAL_Power.c
  targets/ESP32/_nanoCLR/target_platform.h.in
Labels: Type: enhancement, Platform: ESP32

#2645 Fix open file in read update mode while writing
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_FileStream.cpp
Labels: Type: enhancement
