Repository nanoframework/nf-interpreter, pull requests merged in 2023-10, with the labels that each got.

#2782 Console.Write now produces output on all build flavours
  src/CLR/CorLib/corlib_native_System_Diagnostics_Debug.cpp
Labels: Type: enhancement, Area: Common libs, Breaking-change, hacktoberfest-accepted

#2783 Rework exception processing
  src/CLR/CorLib/corlib_native_System_Exception.cpp
  src/CLR/Core/Thread.cpp
Labels: Type: enhancement, Area: Common libs, Breaking-change, hacktoberfest-accepted

#2785 Add if defined condition for ChibiOS ipv6
  targets/ChibiOS/_include/lwipopts.h
Labels: Area: Config-and-Build, Platform: STM32

#2786 Add asserts to several GC related functions
  src/CLR/Core/CLR_RT_HeapCluster.cpp
Labels: Area: Config-and-Build

#2787 Fix declaration in Heap_Relocate()
  src/CLR/Core/GarbageCollector_Compaction.cpp
Labels: Area: Config-and-Build

#2789 Various fixes in ST_NUCLEO64_F091RC
  targets/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/ChibiOS/ST_NUCLEO64_F091RC/board.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/common/Device_BlockStorage-DEBUG.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/launch.json
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/STM32F091xC_booter-DEBUG.ld
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/mcuconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/STM32F091xC_CLR-DEBUG.ld
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/mcuconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/target_common.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/target_system_io_ports_config.cpp
Labels: Type: bug, Area: Config-and-Build, Platform: STM32, hacktoberfest-accepted

#2788 `DateTime` and `TimeSpan` are not handled as primitive types anymore
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/CLR/CorLib/corlib_native_System_DateTime.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_FieldInfo.cpp
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Core/Interpreter.cpp
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.cpp
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.vcxproj
  src/CLR/Core/TypeSystemLookup.cpp
  src/CLR/Debugger/Debugger.cpp
  src/CLR/Include/nanoCLR_Types.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_TouchEventProcessor.cpp
  targets/ChibiOS/_nanoCLR/nanoFramework.Hardware.Stm32/nf_hardware_stm32_native_nanoFramework_Hardware_Stm32_RTC.cpp
Labels: Type: enhancement, Area: Common libs, Breaking-change

#2795 Work CI-CD
  targets/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build

#2794 Fix creation of `DateTime` and `TimeSpan` objects
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/CLR/CorLib/corlib_native_System_DateTime.cpp
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
  src/CLR/Core/TypeSystemLookup.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_File.cpp
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_File.cpp
Labels: Type: bug, Area: Common libs, Breaking-change

#2797 Misc Devcontainer fixes
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.ChibiOS
  config/user-tools-repos.TEMPLATE.json
Labels: Area: Dev-Containers

#2766 Fix Dockerfile.TI
  .devcontainer/Dockerfile.TI
  .devcontainer/sources/Dockerfile.TI
  targets/TI_SimpleLink/_common/WireProtocol_HAL_Interface.c
  targets/TI_SimpleLink/_nanoCLR/targetPAL.c
Labels: Area: Dev-Containers

#2799 Update Espressif IDF to v4.4.6
  .devcontainer/Dockerfile.ESP32
  .devcontainer/sources/Dockerfile.ESP32
  azure-pipelines-nightly.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines.yml
  targets/ESP32/CMakeLists.txt
Labels: Type: dependencies, Area: Dev-Containers

#2800 Update Mbed TLS to v2.28.5
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  src/PAL/COM/sockets/ssl/MbedTLS/nf_mbedtls_config.h
  targets/ChibiOS/CMakeLists.txt
Labels: Type: dependencies, hacktoberfest-accepted, Area: Dev-Containers

#2803 Add hashing and cryptography libraries
  CMake/Modules/FindNF_NativeAssemblies.cmake
  CMake/Modules/FindnanoFramework.System.IO.Hashing.cmake
  CMake/Modules/FindnanoFramework.System.Security.Cryptography.cmake
  CMake/binutils.ChibiOS.cmake
  CMake/binutils.FreeRTOS.cmake
  CMake/binutils.common.cmake
  CMake/xtensa-esp32.json
  CMake/xtensa-esp32c3.json
  CMake/xtensa-esp32s2.json
  CMake/xtensa-esp32s3.json
  src/nanoFramework.System.IO.Hashing/nf_sys_io_hashing.cpp
  src/nanoFramework.System.IO.Hashing/nf_sys_io_hashing.h
  src/nanoFramework.System.Security.Cryptography/nf_sys_sec_cryptography.cpp
  src/nanoFramework.System.Security.Cryptography/nf_sys_sec_cryptography.h
  src/nanoFramework.System.Security.Cryptography/nf_sys_sec_cryptography_System_Security_Cryptography_HMACSHA256.cpp
  targets/AzureRTOS/SiliconLabs/SL_STK3701A/CMakePresets.json
  targets/AzureRTOS/SiliconLabs/_common/nanoSupport_CRC32.c
  targets/AzureRTOS/SiliconLabs/_nanoCLR/nanoFramework.System.IO.Hashing/nf_sys_io_hashing_System_IO_Hashing_Crc32.cpp
  targets/ChibiOS/CMakeLists.txt
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/CMakePresets.json
  targets/ChibiOS/_common/nanoSupport_CRC32.c
  targets/ChibiOS/_nanoCLR/nanoFramework.System.IO.Hashing/nf_sys_io_hashing_System_IO_Hashing_Crc32.cpp
  targets/ChibiOS/_nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.c
  targets/ChibiOS/_nf-overlay/os/hal/ports/STM32/LLD/CRCv1/crc_lld.h
  targets/ESP32/_nanoCLR/nanoFramework.System.IO.Hashing/nf_sys_io_hashing_System_IO_Hashing_Crc32.cpp
Labels: Type: enhancement, Area: Config-and-Build, hacktoberfest-accepted

#2804 Add STM32F767xx to PWM
  targets/ChibiOS/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp
Labels: Type: enhancement
