Repository nanoframework/nf-interpreter, pull requests merged in 2023-03, with the labels that each got.

#2586 Fix ChibiOS SVN server URL
  .devcontainer/Dockerfile.All
  .devcontainer/Dockerfile.AzureRTOS
  .devcontainer/Dockerfile.ChibiOS
  .devcontainer/scripts/git-pull-repos.sh
  .devcontainer/sources/Dockerfile.All
  .devcontainer/sources/Dockerfile.AzureRTOS
  .devcontainer/sources/Dockerfile.ChibiOS
  targets/ChibiOS/CMakeLists.txt
Labels: Area: Config-and-Build, Area: Dev-Containers

#2591 Fix versioning of CLR
  src/CLR/Core/Core.vcxproj
  src/CLR/WireProtocol/WireProtocol.vcxproj
Labels: Area: Config-and-Build

#2584 Updates for Pairing security and authentication
  CMake/Modules/FindnanoFramework.Device.Bluetooth.cmake
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/esp32_nimble.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_ble.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEAdvertisementWatcher.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothLEDevice.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattReadRequest.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattServiceProvider.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattWriteRequest.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_Security.cpp
Labels: Type: bug, Type: enhancement, Type: documentation, Type: dependencies, Platform: ESP32

#2592 Fix version parsing in nanoCLR CLI
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsProcessor.cs
Labels: Type: bug, Platform: Virtual Device & WIN32

#2588 Adding Generic Graphic Driver implementation
  README.md
  README.zh-cn.md
  azure-pipelines-nightly.yml
  src/nanoFramework.Graphics/Graphics/Displays/Display.h
  src/nanoFramework.Graphics/Graphics/Displays/DisplayInterface.h
  src/nanoFramework.Graphics/Graphics/Displays/GC9A01_240x240_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Generic_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ILI9341_XXXxYYY_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ILI9342_320x240_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/Otm8009a_DSI_Video_Mode.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1306_128x64.cpp
  src/nanoFramework.Graphics/Graphics/Displays/SSD1331_94x64_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7735S_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Font.cpp
  targets/ESP32/CMakePresets.json
Labels: Type: enhancement

#2593 Add option to load local instance of nanoCLR
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandLineOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExitCode.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/Program.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/nanoFramework.nanoCLR.CLI.csproj
  targets/netcore/nanoFramework.nanoCLR.Host/Interop/nanoCLR.cs
  targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHost.cs
  targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#2596 Default for loop after exit is now false
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandLineOptions.cs
Labels: Type: enhancement, Platform: Virtual Device & WIN32, Breaking-change

#2597 Add diagnostic output of nanoCLR DLL
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.Host/Interop/nanoCLR.cs
  targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#2598 Fix output of nanoCLR version
  nf.props
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.cpp
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.h
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Type: bug, Platform: Virtual Device & WIN32

#2599 Default verbosity is now normal
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandLineOptions.cs
Labels: Type: enhancement, Platform: Virtual Device & WIN32, Breaking-change

#2594 Adjusting Generic Graphic drivers to work with broader variety of drivers
  src/nanoFramework.Graphics/Graphics/Displays/Display.h
  src/nanoFramework.Graphics/Graphics/Displays/DisplayInterface.h
  src/nanoFramework.Graphics/Graphics/Displays/Generic_SPI.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.h
  src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
Labels: Type: enhancement, Area: Common libs, Type: dependencies

#2601 Bluetooth Generic access changes
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/esp32_nimble.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/nimble_utils.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_ble.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
Labels: Type: bug, Type: dependencies, Platform: ESP32

#2602 Adding support for RMT for ESP32 C3
  targets/ESP32/CMakeLists.txt
  targets/ESP32/CMakePresets.json
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_TransmitterChannel.cpp
Labels: Type: enhancement, Platform: ESP32, Series: ESP32C3

#2604 Adding I2C Fast Mode Plus
  src/System.Device.I2c/sys_dev_i2c_native.cpp
  src/System.Device.I2c/sys_dev_i2c_native.h
  targets/AzureRTOS/ST/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/ESP32/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/TI_SimpleLink/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
Labels: Type: enhancement

#2606 Adding Pulse Count for ESP32 and ESP32-S2/S3
  CMake/Modules/FindnanoFramework.Hardware.Esp32.cmake
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native_System_Device_Gpio_GpioPulseCounter.cpp
Labels: Type: enhancement, Type: dependencies, Platform: ESP32

#2609 Fixing Hardware.Esp32 definition
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.ESP32/nanoFramework_hardware_esp32_native.cpp
Labels: Type: bug

#2608 Fix LilygoTwatch2021 not building
  targets/ESP32/_IDF/sdkconfig.default_pico_ble_rev3
Labels: Area: Config-and-Build

#2612 Addjusting DateTime conversion to add ISO 8601 short format
  src/CLR/CorLib/corlib_native_System_Convert.cpp
Labels: Type: enhancement, Area: Common libs

#2611 Fix field name accessing ReceiverChannelSettings
  targets/ESP32/_nanoCLR/nanoFramework.Hardware.Esp32.Rmt/nanoFramework_hardware_esp32_rmt_native_nanoFramework_Hardware_Esp32_Rmt_ReceiverChannel.cpp
Labels: Type: bug, Platform: ESP32
