Repository nanoframework/nf-interpreter, pull requests merged in 2024-12, with the labels that each got.

#3008 Sd card map pins, drive index & fix events
  src/HAL/Include/nanoHAL_System_IO_FileSystem.h
  src/System.IO.FileSystem/nf_sys_io_filesystem.cpp
  src/System.IO.FileSystem/nf_sys_io_filesystem.h
  targets/ESP32/_common/DeviceMapping_common.cpp
  targets/ESP32/_common/ESP32_DeviceMapping.cpp
  targets/ESP32/_common/ESP32_S3_DeviceMapping.cpp
  targets/ESP32/_common/Target_System_IO_FileSystem.c
  targets/ESP32/_include/Esp32_DeviceMapping.h
  targets/ESP32/_nanoCLR/System.Device.Gpio/cpu_gpio.cpp
  targets/ESP32/_nanoCLR/System.IO.FileSystem/nf_sys_io_filesystem_nanoFramework_System_IO_FileSystem_SDCard.cpp
Labels: Type: bug, Type: dependencies, Platform: ESP32

#3047 Fixing git config for cloning repos in dev containers
  .devcontainer/All/Dockerfile.All
  .devcontainer/All/devcontainer.json
  .devcontainer/AzureRTOS/Dockerfile.AzureRTOS
  .devcontainer/AzureRTOS/devcontainer.json
  .devcontainer/ChibiOS/Dockerfile.ChibiOS
  .devcontainer/ChibiOS/devcontainer.json
  .devcontainer/ESP32/Dockerfile.ESP32
  .devcontainer/ESP32/devcontainer.json
  .devcontainer/FreeRTOS-NXP/Dockerfile.FreeRTOS-NXP
  .devcontainer/FreeRTOS-NXP/devcontainer.json
  .devcontainer/TI/Dockerfile.TI
  .devcontainer/TI/devcontainer.json
Labels: Area: Dev-Containers

#3048 Adjust native memory for ESP32_S3 without PSRAM
  targets/ESP32/_nanoCLR/Memory.cpp
Labels: Type: enhancement

#3051 Add asserts and sanity checks on HB Array handling
  src/CLR/Core/CLR_RT_HeapBlock_Array.cpp
Labels: Type: enhancement, Area: Common libs

#3050 Add asserts on GC compaction
  src/CLR/Core/GarbageCollector_Compaction.cpp
Labels: Type: enhancement, Area: Common libs

#3049 Improvements in WP packet header handler
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: enhancement, Area: Common libs

#3052 Improve sanity check with WP sync code
  src/CLR/WireProtocol/WireProtocol_Message.c
Labels: Type: bug, Area: Common libs

#3054 Add generic screen to ESP32_S3 target
  README.md
  targets/ESP32/CMakePresets.json
Labels: Type: enhancement

#3053 Optimise ESP32_S2 targets
  README.md
  README.zh-cn.md
  azure-pipelines-nightly.yml
  azure-pipelines.yml
  targets/ESP32/CMakePresets.json
Labels: Type: enhancement

#3055 Update Gecko SDK to v4.4.5
  targets/AzureRTOS/SiliconLabs/CMakeLists.txt
Labels: Type: dependencies, Series: SL-EFM32GG11

#3056 Migrate SPI code to new Gecko SDK
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.Spi/cpu_spi.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.Spi/nf_gecko_spi_driver.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.Spi/nf_gecko_spi_driver.h
Labels: Type: dependencies, Series: SL-EFM32GG11

#3057 Fix GetLength reseting file position
  targets/ESP32/_littlefs/littlefs_FS_Driver.cpp
Labels: Type: bug, Platform: ESP32

#3059 Fix ASSERT in GC heap compact
  src/CLR/Core/GarbageCollector_Compaction.cpp
Labels: Type: enhancement, Area: Common libs
