Repository nanoframework/nf-interpreter, pull requests merged in 2024-06, with the labels that each got.

#2946 Add Generic display to ESP32_S3_BLE
  targets/ESP32/CMakePresets.json
Labels: Type: enhancement

#2947 Error in pico sdkconfig causing overnight pico build to fail
  targets/ESP32/_IDF/sdkconfig.default_pico
Labels: Type: bug

#2948 README improvements
  README.md
Labels: Type: documentation

#2949 Update STM cube packages
  CMake/Modules/STM32_CubePackage.cmake
  targets/AzureRTOS/ST/ORGPAL_PALTHREE/stm32f7xx_hal_conf.h
  targets/ChibiOS/ORGPAL_PALTHREE/stm32f7xx_hal_conf.h
  targets/ChibiOS/ORGPAL_PALX/stm32f7xx_hal_conf.h
Labels: Series: STM32xx, Type: dependencies, Platform: STM32

#2950 Flash Size in bootloader causing flashing issues with firmware built with IDF5.x
  targets/ESP32/_IDF/sdkconfig.default
  targets/ESP32/_IDF/sdkconfig.default.esp32c3
  targets/ESP32/_IDF/sdkconfig.default.esp32c6
  targets/ESP32/_IDF/sdkconfig.default.esp32h2
  targets/ESP32/_IDF/sdkconfig.default.esp32s2
  targets/ESP32/_IDF/sdkconfig.default.esp32s3
  targets/ESP32/_IDF/sdkconfig.default_ble.esp32s3
  targets/ESP32/_IDF/sdkconfig.default_ble_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_ble.esp32
  targets/ESP32/_IDF/sdkconfig.default_nopsram_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_pico
  targets/ESP32/_IDF/sdkconfig.default_pico_ble_rev3
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32
  targets/ESP32/_IDF/sdkconfig.default_rev3.esp32c3
  targets/ESP32/_IDF/sdkconfig.default_rev3_ipv6.esp32
  targets/ESP32/_IDF/sdkconfig.default_rev3_noconsole.esp32c3
Labels: Type: bug, Status: in progress, Platform: ESP32

#2951 After IDF upgrade PICO native memory too low
  targets/ESP32/CMakePresets.json
  targets/ESP32/_IDF/sdkconfig.default_pico
Labels: Type: bug, Platform: ESP32

#2952 Add the new target for Olimex POE with wrover module
  README.md
  azure-pipelines-nightly.yml
  targets/ESP32/CMakePresets.json
Labels: Type: enhancement, Type: documentation, Status: DONE, Platform: ESP32

#2953 Fix typo in azure nightly
  azure-pipelines-nightly.yml
Labels: Type: bug

#2955 Fix config for new ESP32_OLIMEX_WROVER target
  targets/ESP32/CMakePresets.json
Labels: Type: bug, Platform: ESP32

#2957 Fix mutex in PAL Events for virtual nanoCLR
  azure-pipelines.yml
  src/CLR/Core/Core.h
  src/CLR/Include/nanoCLR_Application.h
  targets/netcore/nanoFramework.nanoCLR/CLRStartup.cpp
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.cpp
  targets/win32/Include/Win32TimerQueue.h
  targets/win32/nanoCLR/CLRStartup.cpp
  targets/win32/nanoCLR/Various.cpp
  targets/win32/nanoCLR/main.cpp
  targets/win32/nanoCLR/targetPAL_Events.cpp
Labels: Type: bug, Area: Config-and-Build, Area: Interpreter, Platform: Virtual Device & WIN32

#2963 Improve check to create stack trace for exception
  src/CLR/CorLib/corlib_native_System_Exception.cpp
Labels: Type: enhancement

#2964 Improvements in Gecko USB stack usage
  CMake/Modules/FindGecko_SDK.cmake
  targets/AzureRTOS/SiliconLabs/_common/nano_sl_usbd_core.c
Labels: Type: bug, Area: Config-and-Build

#2966 Update bluetooth checksum due to PR #82
  targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native.cpp
Labels: Type: enhancement

#2967 Fix issues with Wire Protocol in ST_NUCLEO64_F091RC
  targets/ChibiOS/ST_NUCLEO64_F091RC/CMakeLists.txt
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoBooter/main.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/halconf.h
  targets/ChibiOS/ST_NUCLEO64_F091RC/nanoCLR/main.c
  targets/ChibiOS/ST_NUCLEO64_F091RC/target_common.c
Labels: Type: bug, Area: Config-and-Build, Series: STM32xx, Platform: STM32

#2965 Update DLL and license for virtual serial bridge
  targets/netcore/nanoFramework.nanoCLR.CLI/License/vspt.vsptlic
  targets/netcore/nanoFramework.nanoCLR.CLI/Vendor/hhdvspkit.interop.dll
Labels: Type: dependencies

#2968 COM1 not available on C6 and Heap corruption
  src/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort__.cpp
  targets/ESP32/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Platform: ESP32

#2971 Update llvm to 18.1.7
  azure-pipelines-templates/download-install-llvm.yml
Labels: Area: Config-and-Build

#2970 Rework OOM exception
  src/CLR/CorLib/corlib_native_System_Exception.cpp
  src/CLR/Core/Execution.cpp
  src/CLR/Core/GarbageCollector.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Diagnostics/Profiler.cpp
  src/CLR/Include/nanoCLR_Runtime.h
Labels: Type: bug, Type: enhancement, Area: Interpreter

#2972 Work CI-CD
  azure-pipelines-nightly.yml
  azure-pipelines-templates/build-azurertos-targets.yml
  azure-pipelines-templates/build-chibios-stm32-targets.yml
  azure-pipelines-templates/build-espressif-esp32-targets.yml
  azure-pipelines-templates/build-freertos-nxp-targets.yml
  azure-pipelines-templates/build-preparations.yml
  azure-pipelines-templates/build-ti-simplelink-targets.yml
  azure-pipelines-templates/check-code-style.yml
  azure-pipelines-templates/download-hexdfu.yml
  azure-pipelines-templates/download-install-arm-gcc-toolchain.yml
  azure-pipelines-templates/download-install-esp32-build-components.yml
  azure-pipelines-templates/download-install-llvm.yml
  azure-pipelines-templates/download-install-ninja.yml
  azure-pipelines-templates/download-srecord.yml
  azure-pipelines-templates/nb-gitversioning.yml
  azure-pipelines-templates/pack-publish-managed-helpers.yml
  azure-pipelines-templates/pack-publish-ti-sl-managed-helpers.yml
  azure-pipelines-templates/publish-cloudsmith.yml
  azure-pipelines-templates/publish-nanoclr.yml
  azure-pipelines-templates/setup-cmake-user-presets.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#2973 Revert "Improvements in Gecko USB stack usage (#2964)"
  CMake/Modules/FindGecko_SDK.cmake
  targets/AzureRTOS/SiliconLabs/_common/nano_sl_usbd_core.c
Labels: Type: bug, Area: Config-and-Build, Series: SL-EFM32GG11

#2626 Improve chibios and HAL config for STM32F769I
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/chconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/halconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoBooter/halconf_nf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/chconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf.h
  targets/ChibiOS/ST_STM32F769I_DISCOVERY/nanoCLR/halconf_nf.h
Labels: Type: enhancement

#2969 Updates to OpenThread support
  CMake/binutils.ESP32.cmake
  CMake/xtensa-esp32c6.json
  CMake/xtensa-esp32h2.json
  README.md
  azure-pipelines-nightly.yml
  src/HAL/Include/nanoHAL_v2.h
  src/PAL/Include/nanoPAL_Sockets.h
  src/PAL/Lwip/lwIP_Sockets.cpp
  src/PAL/Lwip/lwIP_Sockets.h
  src/PAL/Lwip/lwIP_Sockets_functions.cpp
  targets/ESP32/CMakePresets.json
  targets/ESP32/_IDF/esp32c6/partitions_nanoclr_16mb.csv
  targets/ESP32/_IDF/esp32c6/partitions_nanoclr_4mb.csv
  targets/ESP32/_IDF/esp32c6/partitions_nanoclr_8mb.csv
  targets/ESP32/_IDF/sdkconfig.default.esp32c6
  targets/ESP32/_Network/NF_ESP32_OpenThread.cpp
  targets/ESP32/_common/Target_Network.cpp
  targets/ESP32/_common/targetHAL_ConfigurationManager.cpp
  targets/ESP32/_common/targetHAL_Network.cpp
  targets/ESP32/_include/NF_ESP32_Network.h
  targets/ESP32/_nanoCLR/nanoFramework.Networking.Thread/net_thread_native.cpp
  targets/ESP32/_nanoCLR/nanoFramework.Networking.Thread/net_thread_native.h
  targets/ESP32/_nanoCLR/nanoFramework.Networking.Thread/net_thread_native_nanoFramework_Networking_Thread_OpenThread.cpp
Labels: Type: bug, Type: enhancement, Type: documentation, Platform: ESP32, Series: ESP32C6, Series:ESP32H2
