Repository nanoframework/nf-interpreter, pull requests merged in 2024-09, with the labels that each got.

#3014 Fix cache invalidation for SPI transfer
  targets/ChibiOS/_nanoCLR/System.Device.Spi/cpu_spi.cpp
Labels: Type: bug, Platform: STM32

#3016 Fix UART config for RS485
  targets/ChibiOS/_nanoCLR/System.IO.Ports/sys_io_ser_native_System_IO_Ports_SerialPort.cpp
Labels: Type: bug, Type: enhancement, Platform: STM32

#3015 Protection against missing LITTLEFS_PATH
  targets/netcore/littlefs/littlefs.vcxproj
  targets/netcore/nanoFramework.nanoCLR/nanoFramework.nanoCLR.vcxproj
Labels: Area: Config-and-Build

#3019 Wrap GC informational messages
  src/CLR/Core/Execution.cpp
  src/CLR/Core/GarbageCollector.cpp
Labels: Area: Config-and-Build, Area: Interpreter, Breaking-change

#3021 Fix format string for 64bits vars
  src/CLR/Core/Execution.cpp
  src/CLR/Diagnostics/Profiler.cpp
Labels: Area: Config-and-Build

#3022 Fix block storage declaration for ESP32 Configuration Partition and Usage Size
  targets/ESP32/_common/Device_BlockStorage.c
Labels: Type: bug

#3024 Fix littlefs mount on virtual device
  targets/netcore/littlefs/hal_littlefs.c
  targets/netcore/nanoFramework.nanoCLR/target_littlefs.cpp
Labels: Type: enhancement, Platform: Virtual Device & WIN32

#3020 Remove private implementation of printf
  CMake/Modules/FindNF_CoreCLR.cmake
  src/CLR/CorLib/CorLib.h
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/CorLib/corlib_native_System_Number.cpp
  src/CLR/Core/Core.vcxproj
  src/CLR/Core/Core.vcxproj.filters
  src/CLR/Diagnostics/Diagnostics.h
  src/CLR/Diagnostics/Diagnostics.vcxproj
  src/CLR/Diagnostics/Info_Safeprintf.cpp
  src/CLR/Helpers/nanoprintf/nanoprintf.c
  src/CLR/Helpers/nanoprintf/nanoprintf.h
  targets/AzureRTOS/_common/nanoCLR/nanoCRT.cpp
  targets/ChibiOS/_nanoCLR/nanoCRT.cpp
  targets/ESP32/_Network/NF_ESP32_OpenThread.cpp
  targets/ESP32/_nanoCLR/nanoCRT.cpp
  targets/FreeRTOS/_common/nanoCLR/nanoCRT.cpp
  targets/TI_SimpleLink/_nanoCLR/nanoCRT.cpp
Labels: Area: Config-and-Build, Type: dependencies

#3025 Update Sys.Collections to use key hash code as parameter
  src/nanoFramework.System.Collections/nf_system_collections.cpp
  src/nanoFramework.System.Collections/nf_system_collections.h
  src/nanoFramework.System.Collections/nf_system_collections_System_Collections_Hashtable.cpp
Labels: Type: enhancement, Type: dependencies

#3023 Metadata of native assemblies is now generated and exposed in virtual device
  .editorconfig
  CMake/Modules/FindNF_NativeAssemblies.cmake
  spelling_exclusion.dic
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ClrInstanceOperationsProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/CommonOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandLineOptions.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExecuteCommandProcessor.cs
  targets/netcore/nanoFramework.nanoCLR.CLI/ExitCode.cs
  targets/netcore/nanoFramework.nanoCLR.Host/Interop/nanoCLR.cs
  targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
  targets/netcore/nanoFramework.nanoCLR.Host/NativeAssemblyDetails.cs
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.cpp
  targets/netcore/nanoFramework.nanoCLR/nanoCLR_native.h
Labels: Type: enhancement, Area: Config-and-Build, Platform: Virtual Device & WIN32
