Repository nanoframework/nf-interpreter, pull requests merged in 2025-01, with the labels that each got.

#3060 Update HDD soft license and interop dll
  targets/netcore/nanoFramework.nanoCLR.CLI/License/vspt.vsptlic
  targets/netcore/nanoFramework.nanoCLR.CLI/Vendor/hhdvspkit.interop.dll
Labels: Platform: Virtual Device & WIN32, Type: dependencies

#3062 Fix protecting HB from GC
  src/System.Device.Spi/sys_dev_spi_native_System_Device_Spi_SpiDevice.cpp
  targets/AzureRTOS/ST/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.UsbStream/sys_dev_usbstream_native_System_Device_Usb_UsbStream.cpp
  targets/ChibiOS/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/TI_SimpleLink/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
Labels: Type: bug, Type: enhancement, Area: Common libs, Platform: STM32, Platform: NXP, Platform: TI-SimpleLink, Platform: Azure-RTOS

#3063 Proper handling thread creation failure
  targets/AzureRTOS/ST/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/System.Device.I2c/sys_dev_i2c_native_System_Device_I2c_I2cDevice.cpp
  targets/AzureRTOS/SiliconLabs/_nanoCLR/nanoFramework.Device.OneWire/nf_dev_onewire_nanoFramework_Device_OneWire_OneWireHost.cpp
Labels: Type: bug, Platform: Azure-RTOS

#3064 Work CI-CD
  azure-pipelines-nightly.yml
  azure-pipelines.yml
Labels: Area: Config-and-Build

#3065 Add Flash Silabs EFM32 GG11 task
  .vscode/tasks.TEMPLATE.json
Labels: Type: enhancement, Area: Infrastructure-and-Organization

#3067 Fix format string to output x64 addresses
  src/CLR/Core/Core.h
  src/CLR/Core/GarbageCollector_Info.cpp
Labels: Type: bug, Area: Common libs

#3068 Stack trace is now generated despite debugger state
  src/CLR/CorLib/corlib_native_System_Exception.cpp
Labels: Type: enhancement, Area: Common libs, Breaking-change

#3069 Rework test of pointers at GC to use malloc instead of C++ constructors
  src/CLR/Core/GarbageCollector_Info.cpp
Labels: Type: enhancement

#3071 Add missing compiler definition for DEBUG
  src/CLR/CorLib/CorLib.vcxproj
  src/CLR/Core/Core.vcxproj
  src/CLR/Core/FileStream/FileStream.vcxproj
  src/CLR/Core/Hardware/Hardware.vcxproj
  src/CLR/Core/Hardware/Hardware_stub.vcxproj
  src/CLR/Core/InterruptHandler/InterruptHandler.vcxproj
  src/CLR/Core/InterruptHandler/InterruptHandler_stub.vcxproj
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher.vcxproj
  src/CLR/Core/NativeEventDispatcher/NativeEventDispatcher_stub.vcxproj
  src/CLR/Core/RPC/RPC.vcxproj
  src/CLR/Core/RPC/RPC_stub.vcxproj
  src/CLR/Core/Serialization/Serialization.vcxproj
  src/CLR/Core/Serialization/Serialization_stub.vcxproj
  src/CLR/Debugger/Debugger.vcxproj
  src/CLR/Debugger/Debugger_stub.vcxproj
  src/CLR/Diagnostics/Diagnostics.vcxproj
  src/CLR/Diagnostics/Diagnostics_stub.vcxproj
  src/CLR/Messaging/Messaging.vcxproj
  src/CLR/Messaging/Messaging_stub.vcxproj
  src/CLR/Startup/Startup.vcxproj
  src/CLR/System.Math/System.Math.vcxproj
  src/CLR/WireProtocol/WireProtocol.vcxproj
  src/DeviceInterfaces/Networking.Sntp/Networking.Sntp.vcxproj
  src/DeviceInterfaces/System.Net/System.Net.vcxproj
  src/System.Device.Gpio/System.Device.Gpio.vcxproj
  src/System.Device.UsbStream/System.Device.UsbStream.vcxproj
  src/System.IO.FileSystem/System.IO.FileSystem.vcxproj
  src/System.IO.Ports/System.IO.Ports.vcxproj
  src/System.Runtime.Serialization/System.Runtime.Serialization.vcxproj
  src/Windows.Storage/Windows.Storage.vcxproj
  src/nanoFramework.ResourceManager/nanoFramework.ResourceManager.vcxproj
  src/nanoFramework.Runtime.Native/Runtime.Native.vcxproj
  src/nanoFramework.System.Collections/System.Collections.vcxproj
  src/nanoFramework.System.Text/System.Text.vcxproj
  targets/netcore/littlefs/littlefs.vcxproj
  targets/netcore/nanoFramework.nanoCLR/nanoFramework.nanoCLR.vcxproj
  targets/win32/nanoCLR/nanoCLR.vcxproj
Labels: Area: Config-and-Build, Platform: Virtual Device & WIN32

#3072 Fix output of heap allocation info
  src/CLR/Core/Execution.cpp
Labels: Type: bug, Area: Common libs

#3074 Fix asserts
  src/CLR/Core/CLR_RT_HeapCluster.cpp
  src/CLR/Core/GarbageCollector_Compaction.cpp
  src/CLR/Core/GarbageCollector_Info.cpp
Labels: Type: bug, Type: enhancement, Area: Common libs

#3075 Fix pointers comparison
  src/CLR/Core/CLR_RT_HeapCluster.cpp
  src/CLR/Core/GarbageCollector_Compaction.cpp
Labels: Type: enhancement, Area: Common libs

#3076 Fix usage of uintptr_t accross GC and HeapCluster classes
  src/CLR/Core/CLR_RT_HeapCluster.cpp
  src/CLR/Core/GarbageCollector_Info.cpp
Labels: Type: enhancement, Area: Common libs

#3077 Fixing WirelessAP config retrieve and deployment in Wire Protocol
  src/CLR/Debugger/Debugger.cpp
Labels: Type: bug

#3079 Remove unnecessary memsets from code base
  src/CLR/CorLib/corlib_native_System_Array.cpp
  src/CLR/CorLib/corlib_native_System_Exception.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_Assembly.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_FieldInfo.cpp
  src/CLR/CorLib/corlib_native_System_Reflection_RuntimeFieldInfo.cpp
  src/CLR/CorLib/corlib_native_System_Runtime_CompilerServices_RuntimeHelpers.cpp
  src/CLR/CorLib/corlib_native_System_String.cpp
  src/CLR/CorLib/corlib_native_System_Threading_Interlocked.cpp
  src/CLR/CorLib/corlib_native_System_Threading_SpinWait.cpp
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
  src/CLR/CorLib/corlib_native_System_WeakReference.cpp
  src/CLR/Core/CLR_RT_HeapBlock.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Array.cpp
  src/CLR/Core/CLR_RT_HeapBlock_ArrayList.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Delegate.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Delegate_List.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Lock.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Queue.cpp
  src/CLR/Core/CLR_RT_HeapBlock_Stack.cpp
  src/CLR/Core/CLR_RT_StackFrame.cpp
  src/CLR/Core/Execution.cpp
  src/CLR/Core/Interpreter.cpp
  src/CLR/Core/Serialization/BinaryFormatter.cpp
  src/CLR/Core/Thread.cpp
  src/CLR/Core/TypeSystem.cpp
  src/CLR/Debugger/Debugger.cpp
  src/nanoFramework.Runtime.Native/nf_rt_native_nanoFramework_Runtime_Hardware_SystemInfo.cpp
  src/nanoFramework.System.Collections/nf_system_collections_System_Collections_Hashtable.cpp
  src/nanoFramework.System.Text/nf_system_text_System_Text_UTF8Encoding.cpp
Labels: Type: enhancement

#3080 Fix assert in GC::Heap_Compact
  src/CLR/Core/GarbageCollector_Compaction.cpp
Labels: Type: bug, Area: Common libs

#3082 Fix base64 encode/decode and To/From Base64 string
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/CLR/Helpers/Base64/base64.c
  src/CLR/Helpers/Base64/base64.h
  targets/win32/nanoCLR/base64.cpp
Labels: Type: enhancement, Platform: Virtual Device & WIN32, Area: Common libs

#3083 Improve output messages
  src/CLR/Core/GarbageCollector.cpp
  src/CLR/Core/GarbageCollector_Compaction.cpp
  src/CLR/Core/TypeSystem.cpp
Labels: Type: enhancement, Area: Common libs

#3084 Rework `DateTime` and `TimeSpan`
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
  src/CLR/CorLib/corlib_native_System_Convert.cpp
  src/CLR/CorLib/corlib_native_System_DateTime.cpp
  src/CLR/CorLib/corlib_native_System_TimeSpan.cpp
  src/CLR/Core/TypeSystemLookup.cpp
Labels: Type: bug, Type: enhancement, Area: Common libs, Type: dependencies

#3070 Update mscorlib assembly declarations
  src/CLR/CorLib/corlib_native.cpp
  src/CLR/CorLib/corlib_native.h
Labels: Type: dependencies

#3086 Fix printf
  src/CLR/Diagnostics/Info.cpp
  src/CLR/Diagnostics/Info_Safeprintf.cpp
  src/CLR/Helpers/nanoprintf/nanoprintf.c
Labels: Type: bug, Type: enhancement, Area: Common libs

#3087 Replace dynamic allocation of print buffer
  src/CLR/Diagnostics/Info.cpp
Labels: Type: enhancement
